### ISSUE TITLE
es1.7.2用ik1.4.1报错，请帮忙看看是什么问题？谢谢

### ISSUE THREAD

**Issue by zhaozhiming** [medcl/elasticsearch-analysis-ik#103]
HI all,
我的ES用的是1.7.2，ik分词器是用源码打包的，配置完了之后ES运行没有报错，但是在添加索引的时候(`curl -XPUT http://localhost:9200/index`)就报错了，报错如下，请帮忙看看是啥问题？非常感谢。

```
[2015-10-24 22:00:26,969][DEBUG][action.admin.indices.create] [Stygorr] [index] failed to create
org.elasticsearch.indices.IndexCreationException: [index] failed to create index
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:338)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:371)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer type [ik] or tokenizer for [ik_max_word]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:372)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:336)
        ... 7 more
Caused by: org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [type] with value [ik]
        at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:476)
        at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:464)
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:356)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.analysis.ik.IkAnalyzerProvider
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:474)
```

我的es版本：
```
{
  "status" : 200,
  "name" : "Stygorr",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

我的ik版本：
```
➜  elasticsearch-1.7.2  ll plugins/analysis-ik
total 2504
-rw-r--r--  1 zhaozhiming  staff   1.2M Oct 24 21:41 elasticsearch-analysis-ik-1.4.1.zip
```

我也将ik目录放到config下面了：
```
➜  elasticsearch-1.7.2  ll config
total 40
-rw-rw-r--@  1 zhaozhiming  staff    13K Oct 24 21:47 elasticsearch.yml
drwxr-xr-x  10 zhaozhiming  staff   340B Oct 24 21:45 ik
-rw-rw-r--@  1 zhaozhiming  staff   2.0K Sep 14 09:22 logging.yml
➜  elasticsearch-1.7.2  ll config/ik
total 6024
-rw-r--r--  1 zhaozhiming  staff   705B Oct 24 21:45 IKAnalyzer.cfg.xml
drwxr-xr-x  8 zhaozhiming  staff   272B Oct 24 21:45 custom
-rw-r--r--  1 zhaozhiming  staff   2.9M Oct 24 21:45 main.dic
-rw-r--r--  1 zhaozhiming  staff   123B Oct 24 21:45 preposition.dic
-rw-r--r--  1 zhaozhiming  staff   1.8K Oct 24 21:45 quantifier.dic
-rw-r--r--  1 zhaozhiming  staff   164B Oct 24 21:45 stopword.dic
-rw-r--r--  1 zhaozhiming  staff   192B Oct 24 21:45 suffix.dic
-rw-r--r--  1 zhaozhiming  staff   752B Oct 24 21:45 surname.dic
```

这是我的config文件：
<img width="491" alt="screen shot 2015-10-24 at 10 10 44 pm" src="https://cloud.githubusercontent.com/assets/1436694/10710844/2ca15d18-7a9c-11e5-853c-c2b415b72d37.png">

这是我的java版本：

```
➜  elasticsearch-1.7.2  java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by zhaozhiming** [comment]
不好意思，是我搞错了，原来我拷贝的是elasticsearch-analysis-ik-1.4.1.zip，用带依赖包的Jar包就可以了
```
➜  elasticsearch-1.7.2  ll plugins/analysis-ik
total 42408
-rw-r--r--  1 zhaozhiming  staff    21M Oct 24 22:24 elasticsearch-analysis-ik-1.4.1-jar-with-dependencies.jar
```
