### ISSUE TITLE
执行README的示例可以成功，但是发送analyzer=ik请求报错

### ISSUE THREAD

**Issue by zhaozhiming** [medcl/elasticsearch-analysis-ik#104]
HI， 我安装了ik分词器之后，执行get请求报错（报错信息如下），但是执行README里面的示例又是可以的，请问这大概是什么问题？我的es版本是1.7.2，ik版本是1.4.1，谢谢

```
curl http://localhost:9200/_analyze?pretty&analyzer=ik -d '北京天安门'
{
  "error" : "ElasticsearchIllegalArgumentException[failed to find analyzer [ik]]",
  "status" : 400
}
```
报错：  
```
org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer [ik]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:151)
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:60)
        at org.elasticsearch.action.support.single.custom.TransportSingleCustomOperationAction$AsyncSingleAction$1.run(TransportSingleCustomOperationAction.java:161)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

执行README的例子又是可以的:
```
➜  elasticsearch-2.0.0-rc1  curl -XPOST http://localhost:9200/index/fulltext/_search?pretty  -d'
{
    "query" : { "term" : { "content" : "中国" }},
    "highlight" : {
        "pre_tags" : ["<tag1>", "<tag2>"],
        "post_tags" : ["</tag1>", "</tag2>"],
        "fields" : {
            "content" : {}
        }
    }
}
'
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 0.53699243,
    "hits" : [ {
      "_index" : "index",
      "_type" : "fulltext",
      "_id" : "3",
      "_score" : 0.53699243,
      "_source":
{"content":"中韩渔警冲突调查：韩警平均每天扣1艘中国渔船"}
,
      "highlight" : {
        "content" : [ "中韩渔警冲突调查：韩警平均每天扣1艘<tag1>中国</tag1>渔船" ]
      }
    }, {
      "_index" : "index",
      "_type" : "fulltext",
      "_id" : "4",
      "_score" : 0.46027923,
      "_source":
{"content":"中国驻洛杉矶领事馆遭亚裔男子枪击 嫌犯已自首"}
,
      "highlight" : {
        "content" : [ "<tag1>中国</tag1>驻洛杉矶领事馆遭亚裔男子枪击 嫌犯已自首" ]
      }
    } ]
  }
}
```

我的elasticsearch.yml配置：  
![screen shot 2015-10-26 at 5 33 40 pm](https://cloud.githubusercontent.com/assets/1436694/10725563/d3636cf6-7c07-11e5-96ab-aac0754db263.png)

**Comment by medcl** [comment]
配置文件放了么?

**Comment by zhaozhiming** [comment]
放了，最后一个图就是我的配置文件内容。

不过在某个index下面执行命令是可以的：

```
curl http://localhost:9200/index/_analyze?pretty&analyzer=ik -d '北京天安门'

{
  "tokens" : [ {
    "token" : "北京",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "CN_WORD",
    "position" : 1
  }, {
    "token" : "京",
    "start_offset" : 1,
    "end_offset" : 2,
    "type" : "CN_WORD",
    "position" : 2
  }, {
    "token" : "天安门",
    "start_offset" : 2,
    "end_offset" : 5,
    "type" : "CN_WORD",
    "position" : 3
  }, {
    "token" : "天安",
    "start_offset" : 2,
    "end_offset" : 4,
    "type" : "CN_WORD",
    "position" : 4
  }, {
    "token" : "门",
    "start_offset" : 4,
    "end_offset" : 5,
    "type" : "CN_CHAR",
    "position" : 5
  } ]
}
```

**Comment by zhaozhiming** [comment]
刚试了一下，在2.0下面是可以的，在1.7.2上面就不行。 不过没有关系，我们已经升级到了2.0了，谢谢
