### ISSUE TITLE
#ik1.5.0安装到elasticsearch2.0 启动不成功，报错Unknown Analyzer type 

### ISSUE THREAD

**Issue by zqr688** [medcl/elasticsearch-analysis-ik#109]
>哪位大神能帮忙解决IK报错问题，谢谢
>配置信息：
>index:
    analysis:
      analyzer:
         ik:
            alias: [ik_analyzer]
            type: org.elasticsearch.index.analysis.IkAnalyzerProvider

>配置完后启动elasticsearch2.0报以下错误
>错误描述：
>[2015-11-13 13:52:29,810][WARN ][cluster.action.shard     ] [Blackwulf] [intple][3] received shard failed for [intple][3], node[F9WS4JwQSyWrtYdtj7QwQQ], [P], v[597], s[INITIALIZING], a[id=Y2r2rAwOR_2jGLn4j0BqVw], unassigned_info[[reason=ALLOCATION_FAILED], at[2015-11-13T05:52:29.799Z], details[failed to create index, failure IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]]; ]], indexUUID [T0IQBOx3Tyuo5vRCQBfZkA], message [failed to create index], failure [IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]]; ]
[intple] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]];
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:347)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:298)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:167)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:225)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:323)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:212)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:84)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:137)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:56)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:343)
	... 8 more
[2015-11-13 13:52:29,812][WARN ][indices.cluster          ] [Blackwulf] [[intple][2]] marking and sending shard failed due to [failed to create index]
[intple] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]];
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:347)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:298)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:167)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:225)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:323)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:212)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:84)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:137)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:56)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:343)
	... 8 more

**Comment by medcl** [comment]
你把这行配置去掉吧,新版本不需要配置,直接用了

**Comment by arronli** [comment]
不配置的话 分词器也是不起作用的  没有对内容进行分词  2.0/1.5.0

**Comment by medcl** [comment]
配置文件拷过去了么？

send via my Phone.

**Comment by zqr688** [comment]
谢谢！去掉配置却是OK了！

**Comment by zqr688** [comment]
谢谢！去掉配置却是OK了！

**Comment by oryjk** [comment]
这个是我的配置
index: 
  analysis:                  
    analyzer:      
      ik: 
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word: 
          type: ik
          use_smart: false
      ik_smart: 
          type: ik
          use_smart: true
会报错说，找不到type [ik]
如果我把配置去掉，他会报错说
Caused by: java.lang.IllegalStateException: [index.version.created] is not present in the index settings for index with uuid: [null]

我执行的是curl -XPUT http://localhost:9200/index，希望大神能帮帮我，谢谢

**Comment by InvisibleMoon** [comment]
感谢，相同的问题，这个issue帮了大忙了。

**Comment by jerrychien** [comment]
确实有用，不错，我的是2.1.0的版本

**Comment by oryjk** [comment]
解决了，是因为没有配置正确的原因，正如一楼的同学说的那样，删除不必要的配置就可以了

**Comment by waitgod** [comment]
去掉配置后，ES启动不报错了，但是中文还是没法分词呢？

**Comment by 879229629** [comment]
@waitgod 中文分词解决么，我也遇到同样问题

**Comment by zw963** [comment]
see this issue #207
