### ISSUE TITLE
Elasticsearch启动不了

### ISSUE THREAD

**Issue by zeroly** [medcl/elasticsearch-analysis-ik#122]
ES 2.1
JDK jdk-8u66
下载master分支编译，安装完启动不了，报以下错误
Starting elasticsearch: Exception in thread "main" java.lang.IllegalStateException: version string must be a sequence of nonnegative decimal integers separated by "."'s and may have leading zeros but was ${maven.compiler.target}
	at org.elasticsearch.bootstrap.JarHell.checkVersionFormat(JarHell.java:231)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:124)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
	at org.elasticsearch.node.Node.<init>(Node.java:148)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by medcl** [comment]
33fb6ad67ee52a3d58b749de27bee06cf219daef 已解决

**Comment by zeroly** [comment]
感谢
