### ISSUE TITLE
安装分词插件后，使用时出错

### ISSUE THREAD

**Issue by shang515** [medcl/elasticsearch-analysis-ik#123]
先说安装步骤：
我的ES是2.0版本，所以插件版本用的是1.5.0
1、下载插件
2、解压
3、bin/plugin install file:///.../target/releases/elasticsearch-analysis-ik-1.5.0.zip
4、把config/ik 复制到ES_HOME/config
5、修改config/elasticsearch.yml
6、重启elasticsearch

测试：http://localhost:9200/_analyze?analyzer=ik&pretty=true&text=中华人民共和国

然后elasticsearch报错：
[ERROR][transport                ] [El Muerto] failed to handle exception for action [indices:admin/analyze[s]], handler [org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1@7bb62dda]
java.lang.NullPointerException
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:195)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$700(TransportSingleShardAction.java:115)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1.handleException(TransportSingleShardAction.java:174)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by shang515** [comment]
问题解决，给后来人留个标记。
请注意：**************************************
elasticsearch.yml配置注意：无需配置以下内容方可运行
ik:
    alias: [ik_analyzer]
    type: org.elasticsearch.index.analysis.IkAnalyzerProvider
