### ISSUE TITLE
Elasticsearch 2.1 + ik 1.6 yml配置文件里没有添加，但是设置mapping时报错了

### ISSUE THREAD

**Issue by haien** [medcl/elasticsearch-analysis-ik#125]
{
	"mappings":{
		"article":{
			"_all": {
				"analyzer": "ik_max_word",
				"search_analyzer": "ik_max_word",
				"term_vector": "no",
				"store": "false"
			},
			"properties":{
				"title" : {
					"type":"string"
				},
				"content" :{
					"type":"string"
				},
				"content_cn":{
					"type": "string",
					"analyzer":"ik_max_word",
					"search_analyzer":"i_max_word"
				}
			}
		}
	}
}
报错了
analyzer [i_max_word] not found for field [content_cn]

**Comment by medcl** [comment]
请问解决了么？

**Comment by iranw** [comment]
出现类似问题  无法解决呀
···
{
    "page": {
        "_all": {
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_max_word",
            "term_vector": "no",
            "store": "false"
        },
        "properties": {
            "page_name": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}
···

出现问题如下
···
[2015-12-31 15:29:24,935][INFO ][http                     ] [es1] publish_address {192.168.56.101:9200}, bound_addresses {192.168.56.101:9200}
[2015-12-31 15:29:24,935][INFO ][node                     ] [es1] started
[2015-12-31 15:29:25,051][INFO ][gateway                  ] [es1] recovered [4] indices into cluster_state
[2015-12-31 15:29:25,841][WARN ][cluster.action.shard     ] [es1] [cms_dev][1] received shard failed for [cms_dev][1], node[PossqMLBRFSgI02XL_SQSg], [P], v[4], s[INITIALIZING], a[id=9Gco_nz4QE-uuvQp56EQeA], unassigned_info[[reason=CLUSTER_RECOVERED], at[2015-12-31T07:29:24.949Z]], indexUUID [05WmKX58QC-0U_8ofXpmnw], message [failed to update mappings], failure [MapperParsingException[analyzer [ik_max_word] not found for field [page_name]]]
MapperParsingException[analyzer [ik_max_word] not found for field [page_name]]
	at org.elasticsearch.index.mapper.core.TypeParsers.parseField(TypeParsers.java:261)
	at org.elasticsearch.index.mapper.core.StringFieldMapper$TypeParser.parse(StringFieldMapper.java:163)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:310)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:223)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:121)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:391)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:265)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:418)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:372)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:177)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

···

**Comment by medcl** [comment]
先试试这个项目 http://github.com/medcl/elasticsearch-rtf


send via my Phone.

**Comment by iranw** [comment]
已解决。。。
是我的问题。
问题所在：目前是集群环境，我却在一台机器上安装了ik和mmseg分词扩展，导致设置mapping失败。只要把集群中所有机器安装扩展即可。

ps：谢谢@Medcl
