### ISSUE TITLE
es 2.1,ik 1.6下报错

### ISSUE THREAD

**Issue by dhlwing** [medcl/elasticsearch-analysis-ik#127]
java.lang.IllegalStateException: Unable to initialize plugins
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:111)
        at org.elasticsearch.node.Node.<init>(Node.java:148)
        at org.elasticsearch.node.Node.<init>(Node.java:129)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/httpclient-4.4.1.jar/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
        ... 6 more

**Comment by dhlwing** [comment]
我煞笔了 sorry！

**Comment by wx7614140** [comment]
....
