### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by hongta** [medcl/elasticsearch-analysis-ik#136]
ElasticSearch 2.1.1 和 2.1.0
elasticsearch-analysis-ik 1.6.2 和1.7.0

使用 Quick Example的index (https://github.com/medcl/elasticsearch-analysis-ik#quick-example)
No.4 query with highlighting 可以得到正常的结果.
但使用
curl -XGET http://localhost:9200/index/_search?q=abcd
时得到error
```javascript
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query_fetch",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "index",
        "node": "kAv-eBNXQci0tfVDc9nTxA",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 500
}
```
正常应该是
````javascript
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": [

    ]
  }
}
````

**Comment by hongta** [comment]
Got error when use
curl -XPOST http://localhost:9200/index/_search
```javascript
{
  "query": {
    "term": {
      "_all": "中国"
    }
  }
}
```
500 Response
```javascript
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query_fetch",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "index",
        "node": "kAv-eBNXQci0tfVDc9nTxA",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 500
}
```

**Comment by medcl** [comment]
控制台错误输出能提供一下么？

**Comment by hongta** [comment]
```
curl -XGET http://localhost:9200/index/_search?q=agdr

{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query_fetch",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "index",
        "node": "kAv-eBNXQci0tfVDc9nTxA",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 500
}
```
```
[2016-01-22 10:17:19,968][INFO ][rest.suppressed          ] /index/_search Params: {q=agdr, index=index}
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ; nested: NullPointerException;
        at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:382)
        at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:152)
        at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:99)
        at java.lang.Throwable.printStackTrace(Throwable.java:665)
        at java.lang.Throwable.printStackTrace(Throwable.java:721)
        at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
        at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
        at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.elasticsearch.common.logging.log4j.Log4jESLogger.internalInfo(Log4jESLogger.java:125)
        at org.elasticsearch.common.logging.support.AbstractESLogger.info(AbstractESLogger.java:90)
        at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:131)
        at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
        at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:87)
        at org.elasticsearch.rest.action.support.RestActionListener.onFailure(RestActionListener.java:60)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.raiseEarlyFailure(TransportSearchTypeAction.java:316)
        ... 10 more
Caused by: java.lang.NullPointerException
        at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
        at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
        at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
        at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
        at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
        at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
        at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:467)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more
```
installed plugins
```
ik
license
marvel-agent
```

**Comment by hongta** [comment]
我在docker上建立一个独立的ES 2.1.1,只安装IK插件1.7.0 可以正常使用

**Comment by hongta** [comment]
在多次测试后, 发现在docker 也是有问题
用的是RTF 的 ik 1.7.0
这是我的docker https://github.com/hongta/es-ik

**Comment by medcl** [comment]
恩，我这边也看到同样的错误了，正在看是什么原因

**Comment by medcl** [comment]
es已fix，请更新es至最新版本
