### ISSUE TITLE
安装插件以后将index.analysis.analyzer.default.type: "ik"配置到config/elasticsearch.yml异常

### ISSUE THREAD

**Issue by c890402** [medcl/elasticsearch-analysis-ik#166]
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [ik] for [default]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:320)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
请问下这是差什么没配置吗

**Comment by medcl** [comment]
默认设置目前是es的bug，还未修复

**Comment by medcl** [comment]
已经fix b344f2e7079d4edc8dd5501504886b06f0d23cfc

**Comment by Morriaty-The-Murderer** [comment]
@medcl 为什么我这边还是不行？es版本2.2.0  ik1.8.0
下面两行都不行
```
# index.analysis.analyzer.default.type : "ik_max_word"
index.analysis.analyzer.default.type : "ik"
```
报错：
```
[Unknown Analyzer type [ik] for [default]]
```
default配置成`smartcn`就ok，/_analyze接口也没问题。
