### ISSUE TITLE
MapperParsingException [Mapping definition for [answers] has unsupported parameters:  [tokenizer : ik_smart]]

### ISSUE THREAD

**Issue by simonseed** [medcl/elasticsearch-analysis-ik#171]
Running on a Mac. Using elasticsearch from home brew. I have installed the plugin - see below.

When I put_mapping (using elasticsearch-py http://elasticsearch-py.readthedocs.org/en/master/) trying to use the ik_smart tokenizer I get an error from elasticsearch that it is an unsupported parameter.

Should this work?

Is there something I need to configure beside just installing the plugin?

Something in elasticsearch.yml perhaps?

I have searched the elasticsearch docs but I can not find either a list of config variables or valid values they could hold. And it seems from the README for the elasticsearch-analysis-ik plugin that there is no config needed.

Any pointers on how to get this to work would be great. 

Is there some other documentation I need to read?

Thanks!

## Versions

```shell
barney\simonb[501]: elasticsearch --version
Version: 2.2.0, Build: 8ff36d1/2016-01-27T13:32:39Z, JVM: 1.8.0_74

barney\simonb[504]: /usr/local/Cellar/elasticsearch/2.2.0_1/libexec/bin/plugin list -v
Installed plugins in /mnt/local/localhost/var/libexec/elasticsearch/plugins:
    - analysis-icu
    - elasticsearch-analysis-ik
    - elasticsearch-analysis-mmseg
    - elasticsearch-analysis-pinyin
    - elasticsearch-analysis-stconvert
```

## Mapping

```python
        self.mapping = {
            "properties": {
                "answers": {
                    "type": "string",
                    "analyzer": "ik_smart",
                    "tokenizer": "ik_smart",
                    "search_analyzer": "ik_smart",
                    "include_in_all": "true",
                    "boost": 8
                },
                "real_name": {
                    "type": "string",
                    "tokenizer": "ik_smart",
                    "analyzer": "ik_smart",
                    "search_analyzer": "ik_smart"
                }
            }
        }
```

## elasticsearch error log

```shell
MapperParsingException[Mapping definition for [answers] has unsupported parameters:  [tokenizer : ik_smart]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:165)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:310)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:221)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:138)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:119)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:100)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by medcl** [comment]
@simonseed 
```                    "tokenizer": "ik_smart",
```
please remove this parameter in your mapping,which is not a valid parameter.

**Comment by simonseed** [comment]
Thank you. Which tokenizer do you suggest to use?

**Comment by medcl** [comment]
@simonseed you already set the analyzer, that's all, no tokenizer please!

**Comment by simonseed** [comment]
I see thanks. Sorry for the uninformed question. Could you suggest some documentation sources so I can educate myself. Thanks!

**Comment by medcl** [comment]
@simonseed 
FYI:
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-analysis.html
