### ISSUE TITLE
ealsticsearch 2.2.1安装plugin导致ik加载失败

### ISSUE THREAD

**Issue by jaohaohsuan** [medcl/elasticsearch-analysis-ik#173]
安装方式如下
```
./bin/plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v1.8.1/elasticsearch-analysis-ik-1.8.1.zip --verbose
```
输出
```
-> Installing from https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v1.8.1/elasticsearch-analysis-ik-1.8.1.zip...
Trying https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v1.8.1/elasticsearch-analysis-ik-1.8.1.zip ...
Downloading .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v1.8.1/elasticsearch-analysis-ik-1.8.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
- Plugin information:
Name: analysis-ik
Description: IK Analyzer for Elasticsearch
Site: false
Version: 1.8.1
JVM: true
 * Classname: org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin
 * Isolated: false
Installed analysis-ik into /Users/henry/Downloads/elasticsearch-2.2.1/plugins/analysis-ik
Found config, moving to /Users/henry/Downloads/elasticsearch-2.2.1/config/analysis-ik
Installed analysis-ik into /Users/henry/Downloads/elasticsearch-2.2.1/config/analysis-ik
```
注意到`Found config, moving to /Users/henry/Downloads/elasticsearch-2.2.1/config/analysis-ik`这个过程把原来`plugins/analysis-ik/config`的所有的东西都移到es安装目录下的config了.

结果导致`./bin/elasticsearch`运行时报错

```
[2016-03-29 16:16:47,386][ERROR][ik-analyzer              ] ik-analyzer
java.io.FileNotFoundException: /Users/henry/Downloads/elasticsearch-2.2.1/plugins/analysis-ik/config/ik/IKAnalyzer.cfg.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
....
```
原来默认读取字典的地方位置就不对了

**Comment by medcl** [comment]
暂时手动解压到plugins目录下安装吧

**Comment by medcl** [comment]
从es 2.3.5开始支持plugin安装：

./bin/plugin install org.elasticsearch/elasticsearch-analysis-ik/1.9.5

**Comment by q2444113093** [comment]
哦哦
