### ISSUE TITLE
2.3.2安装完1.9.2版本ik后报错？

### ISSUE THREAD

**Issue by tingking23** [medcl/elasticsearch-analysis-ik#188]
拿到ik1.9.2版本
plugins]$ git clone https://github.com/medcl/elasticsearch-analysis-ik.git

编译
Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-analysis-ik 1.9.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ elasticsearch-analysis-ik ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ elasticsearch-analysis-ik ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ elasticsearch-analysis-ik ---
[INFO] Compiling 30 source files to /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ elasticsearch-analysis-ik ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ elasticsearch-analysis-ik ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.11:test (default-test) @ elasticsearch-analysis-ik ---
[INFO] No tests to run.
[INFO] Surefire report directory: /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/target/surefire-reports
------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ elasticsearch-analysis-ik ---
[INFO] Building jar: /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/target/elasticsearch-analysis-ik-1.9.2.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) @ elasticsearch-analysis-ik >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ elasticsearch-analysis-ik ---
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) @ elasticsearch-analysis-ik <<<
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ elasticsearch-analysis-ik ---
[INFO] Building jar: /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/target/elasticsearch-analysis-ik-1.9.2-sources.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default) @ elasticsearch-analysis-ik ---
[INFO] Reading assembly descriptor: /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/src/main/assemblies/plugin.xml
[INFO] Building zip: /home/peng/elasticsearch-2.3.2/plugins/elasticsearch-analysis-ik/target/releases/elasticsearch-analysis-ik-1.9.2.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.057s
[INFO] Finished at: Wed May 04 10:41:31 EDT 2016
[INFO] Final Memory: 25M/328M
[INFO] ------------------------------------------------------------------------
然后mv改名
[peng@bogon plugins]$ mv elasticsearch-analysis-ik ik

重启es报错
./elasticsearch
[2016-05-04 10:41:49,688][INFO ][node                     ] [Storm] version[2.3.2], pid[23089], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-05-04 10:41:49,688][INFO ][node                     ] [Storm] initializing ...
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [ik]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: /home/peng/elasticsearch-2.3.2/plugins/ik/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by tingking23** [comment]
我安装的时候弄错了，不好意思，现在好了已经。

**Comment by kimboqi** [comment]
我也出现相同的问题 你之前什么地方弄错了啊

**Comment by tingking23** [comment]
不是直接拿编译的包复制过去，要用编译后的release的版本复制到那个plugin目录里面
