### ISSUE TITLE
请问在哪里可以找到IK分词器稍微详细一点的文档

### ISSUE THREAD

**Issue by solidsnake2013** [medcl/elasticsearch-analysis-ik#190]
我遇到了很多问题.
按照首页的方式可以拷贝 可以启动.
但是无法设置mapping

设置了配置文件中的
index.analysis.analyzer.default.type : "ik"
启动一直报错

`
nested: IllegalArgumentException[no default analyzer configured];
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:345)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:298)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:167)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:225)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: no default analyzer configured
	at org.elasticsearch.index.analysis.AnalysisService.<init>(AnalysisService.java:267)
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:865)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:865)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:865)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:858)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:137)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:56)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:343)
`

我又看了首页最下面看到plugins/ik 目录里应该有个config 我拷贝了过去依然报错.

实际上我在第一次仅仅拷贝了ik到plugins后是可以启动的

调用  http://localhost:9200/jdpool/_analyze?analyzer=ik&pretty=true&text=我是中国人

也是可以分词成功.

但毕竟没有引用到具体的索引上.

网上一大堆可配置的. 各个不一样, 也不知道有什么具体的意义..

请问哪里有详细的资料可以让我看如何配置这个分词.
同义词
之类的.

**Comment by medcl** [comment]
analyze能正常分词 说明插件安装说没问题的，具体索引的应用就需要设置mapping了，你可以看一下es的mapping设置文档，本项目的readme也是有例子的啊

**Comment by solidsnake2013** [comment]
就是因为我拷贝了这里的mapping设置, 但是总是提交不成功. 说合并失败之类的话.

**Comment by JohnTian** [comment]
```
  "yourIndex": {
    "_all": {
      "analyzer": "ik_smart"
    }
```

OR

```
      "yourField": {
        "include_in_all": true,
        "analyzer": "ik_smart",
        "term_vector": "with_positions_offsets",
        "boost": 8,
        "store": true,
        "type": "string"
      }
```

Good luck.

**Comment by medcl** [comment]
@solidsnake2013 敢不敢把错误信息贴出来

**Comment by robertjelly** [comment]
我的问题和楼主的类似。调用 http://localhost:9200/jdpool/_analyze?analyzer=ik&pretty=true&text=我是中国人 可以分词成功。但create mapping的时候报如下错误：
{
   "error": {
      "root_cause": [
         {
            "type": "mapper_parsing_exception",
            "reason": "analyzer [ik_max_word] not found for field [content]"
         }
      ],
      "type": "mapper_parsing_exception",
      "reason": "analyzer [ik_max_word] not found for field [content]"
   },
   "status": 400
}  
请问这是什么原因，谢谢

**Comment by ralphQi** [comment]
# 集群里每一个实例都要安装ik插件才行
我昨天就踩了这个坑，忘了在哪个文档里看到集群里随便哪个实例装了ik就可以工作，没错，analyze时的确可以工作，但设置mapping的时候就找不到分词器了

把插件复制到其他实例上去，问题就解决了

**Comment by solidsnake2013** [comment]
谢谢 问题已经解决了 使用的是@JohnTian 的方案
