### ISSUE TITLE
安装IK报错

### ISSUE THREAD

**Issue by killduak** [medcl/elasticsearch-analysis-ik#193]
[2016-05-20 11:48:00,625][INFO ][node                     ] [Bloodhawk] version[2.3.2], pid[13848], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-05-20 11:48:00,625][INFO ][node                     ] [Bloodhawk] initializing ...
[2016-05-20 11:48:01,227][ERROR][bootstrap                ] Exception
ElasticsearchException[Could not find plugin class [org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin]]; nested: ClassNotFoundException[org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin];
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:465)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
	... 8 more

我就是按照你们这个流程来的mvn package  然后target\releases下的
[elasticsearch-analysis-ik-1.9.2.zip](https://github.com/medcl/elasticsearch-analysis-ik/files/273854/elasticsearch-analysis-ik-1.9.2.zip) 解压 copy到elasticsearch-2.3.2\plugins\ik下

**Comment by JohnTian** [comment]
我记得 **elasticsearch-analysis-ik-1.9.2.zip** 拷贝到 **elasticsearch-2.3.2\plugins\ik **下，还要进行下面的操作：
```
$ unzip elasticsearch-analysis-ik-1.9.2.zip && rm elasticsearch-analysis-ik-1.9.2.zip
```

**Comment by medcl** [comment]
解压后的目录结构看一下

**Comment by killduak** [comment]
@JohnTian @medcl 已解决，感谢

**Comment by zonglinyue** [comment]
我用的elasticsearch2.3.1，按照上面步骤做完，解压得到7个文件，config文件夹，commons-codec-1.9.jar，commons-logging-1.2.jar，elasticsearch-analysis-ik-1.9.3.jar，httpclient-4.4.1.jar，httpcore-4.4.1，plugin-descriptor.properties.jar并把.zip删掉了。es启动不起来。在plugin删掉ik就能启动起来。 @JohnTian @killduak @medcl  非常感谢

**Comment by zonglinyue** [comment]
是版本问题。。。Plugin [analysis-ik] is incompatible with Elasticsearch [2.3.1]. Was designed for version [2.3.3]

**Comment by anAngryAnt** [comment]
刚刚我也解决了，总结一下我的解决思路（Elasticsearch5.3.0 和ik-5.3.0）：
1、确定，ik的版本跟Elasticsearch版本对上
2、按照官方README中的安装做法，再多一步，`unzip elasticsearch-analysis-ik-1.9.2.zip && rm elasticsearch-analysis-ik-1.9.2.zip`

tips:如果是Elasticsearch从老版本迁移过来5.x的，如果要配置index analyzer ，index level 的配置在这个版本已经不支持在elasticsearch.yml 中配置了，跟着ik github上的README走就好。
