### ISSUE TITLE
ik-1.9.3 远程热更新自定义词库报错: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tangyu** [medcl/elasticsearch-analysis-ik#223]
Elasticsearch v2.3.3
elasticsearch-analysis-ik-1.9.3

错误日志如下
> 
> [2016-06-27 08:21:08,708][INFO ][ik-analyzer              ] [Dict Loading] http://xxx.xxx.xxx/?method=search.getCustomDict
> [2016-06-27 08:21:08,833][INFO ][ik-analyzer              ] 妖娆
> ...
> [2016-06-27 08:21:08,971][INFO ][ik-analyzer              ] 路飞
> [2016-06-27 08:21:08,972][INFO ][ik-analyzer              ] [Dict Loading] ik/custom/ext_stopword.dic
> [2016-06-27 08:21:08,972][INFO ][ik-analyzer              ] 重新加载词典完毕...
> [2016-06-27 08:21:32,581][WARN ][cluster.routing.allocation.decider] [Wasp] high disk watermark [90%] exceeded on [8ZKba3nMQduNLWdLy8hFlQ][Wasp][/home/data/es2/elasticsearch/nodes/0] free: 576.2mb[7.1%], shards will be relocated away from this node
> [2016-06-27 08:21:32,582][INFO ][cluster.routing.allocation.decider] [Wasp] rerouting shards: [high disk watermark exceeded on one or more nodes]
> [2016-06-27 08:22:02,595][WARN ][cluster.routing.allocation.decider] [Wasp] high disk watermark [90%] exceeded on [8ZKba3nMQduNLWdLy8hFlQ][Wasp][/home/data/es2/elasticsearch/nodes/0] free: 576.2mb[7.1%], shards will be relocated away from this node
> [2016-06-27 08:22:08,294][ERROR][ik-analyzer              ] remote_ext_dict http://xxx.xxx.xxx/?method=search.getCustomDict error!
> java.lang.NullPointerException
> 	at org.wltea.analyzer.dic.Monitor.run(Monitor.java:72)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by Klauszhao** [comment]
求解热更新的扩展思路，还是不太懂啊。
