### ISSUE TITLE
[Resolved] Could not load plugin descriptor for existing plugin [ik]. Was the plugin built before 2.0?

### ISSUE THREAD

**Issue by laoyang360** [medcl/elasticsearch-analysis-ik#231]
I installed ik on win7 successfully, But when I start ES, the follow bugs apper:
Any help would be sincerely appreciate!

[2016-07-07 16:45:29,655][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [ik]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:381)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.NoSuchFileException: c:\elasticsearch-2.3.3\plugins\ik\plugin-descriptor.properties
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	... 7 more

**Comment by laoyang360** [comment]
Ok, I find the reason is: The plugin-descriptor.properties and all the files  generate by Ik installed are must in the file path: C:\elasticsearch-2.3.3\plugins\ik.

**Comment by luoxuehuan** [comment]
$ cd $ES_HOME/plugins/ik
   
   $ unzip elasticsearch-analysis-ik-5.0.0.zip
