### ISSUE TITLE
Likely root cause: java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by hanzhankang** [medcl/elasticsearch-analysis-ik#235]
$ ./bin/elasticsearch
[2016-07-14 00:37:26,554][WARN ][bootstrap                ] Unable to lock JVM Memory: error=78,reason=Function not implemented
[2016-07-14 00:37:26,555][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[2016-07-14 00:37:26,728][INFO ][node                     ] [master01] version[2.3.3], pid[13765], build[218bdf1/2016-05-17T15:40:04Z]
[2016-07-14 00:37:26,728][INFO ][node                     ] [master01] initializing ...
Exception in thread "main" java.lang.IllegalStateException: failed to load bundle [file:~/scala-script/out/master01/elasticsearch-2.3.3/plugins/ik/commons-codec-1.9.jar, file:~/scala-script/out/master01/elasticsearch-2.3.3/plugins/ik/commons-logging-1.2.jar, file:~/scala-script/out/master01/elasticsearch-2.3.3/plugins/ik/elasticsearch-analysis-ik-1.9.3.jar, file:~/scala-script/out/master01/elasticsearch-2.3.3/plugins/ik/httpclient-4.4.1.jar, file:~/scala-script/out/master01/elasticsearch-2.3.3/plugins/ik/httpcore-4.4.1.jar] due to jar hell
Likely root cause: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:174)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:419)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

按主页上的安装说明操作，发现ES无法启动，查看其他资料说是编译环境JDK与运行环境的JDK版本不一致？请问具体是什么意思呢？

**Comment by hanzhankang** [comment]
是否可以做成一个类似于 head 的东西呢？比如下面的命令：

$ bin/plugin install medcl/elasticsearch-analysis-ik
-> Installing medcl/elasticsearch-analysis-ik...
Trying https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip ...
Downloading ............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip


这里是对verify checksum for downloaded plugin验证失败。如果可以的话，安装也会相对容易些。

**Comment by medcl** [comment]
从es2.3.5开始支持plugin安装：
`./bin/plugin install org.elasticsearch/elasticsearch-analysis-ik/1.9.5`
