### ISSUE TITLE
有支持ES2.3.4计划吗？

### ISSUE THREAD

**Issue by lonly197** [medcl/elasticsearch-analysis-ik#236]
Exception
java.lang.IllegalArgumentException: Plugin [analysis-ik] is incompatible with Elasticsearch [2.3.4]. Was designed for version [2.3.3]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by medcl** [comment]
今晚提供

**Comment by only-gale** [comment]
我手贱了，upgrade了一下，结果也是这错，好悲催。如果今晚提供的话， 那我就等等吧

**Comment by icedfish** [comment]
@medcl 能不强制指定版本么？ 避免每次升级小版本得重新部署IK，反正不是不兼容，只是你配置文件改个版本号的事情么。。。

**Comment by medcl** [comment]
@icedfish 现在的机制就是这样，没办法，要求严格一点，确保插件作者对每个版本进行过测试

**Comment by medcl** [comment]
相关讨论 https://github.com/elastic/elasticsearch/issues/15000

**Comment by icedfish** [comment]
如果把支持版本改成2.3.99这样呢？ 作为workround应该可以满足大家需求吧？
