### ISSUE TITLE
es 安装ik后运行报错

### ISSUE THREAD

**Issue by Samuel-liuse** [medcl/elasticsearch-analysis-ik#247]
1.compile
mvn package
copy and unzip target/releases/elasticsearch-analysis-ik-{version}.zip to your-es-root/plugins/ik
2.restart elasticsearch
按照这个流程，运行ES报错（comd是我现在es中的索引）
[2016-07-26 09:45:56,363][WARN ][indices.cluster          ] [Fenris] [[comd][4]] marking and sending shard failed due to [failed to create index]
[comd] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]];
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:294)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:163)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:320)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
	... 9 more

**Comment by medcl** [comment]
yml配置设的什么？

**Comment by Samuel-liuse** [comment]
index:
  analysis:
    analyzer:
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true

**Comment by medcl** [comment]
你把这些都去掉，试试

**Comment by Samuel-liuse** [comment]
好了跑起来了，但是这些是什么作用呢？yml里添加的

**Comment by medcl** [comment]
你的配置已不支持
