### ISSUE TITLE
ES添加IK 2.3.4 启动失败问题

### ISSUE THREAD

**Issue by conhaifeng** [medcl/elasticsearch-analysis-ik#251]
问题1：在elasticsearch.yml中添加  index.analysis.analyzer.default.type: ik ，必须在行首空两格，否则启动失败。同时有些人（ik版本未确定）在行首添加一个空格即可。

问题2：最新版本ik是否还需要在elasticsearch.yml添加ik的配置语句，在readme中没有详细说明这点，但在issues中有些添加，有些被要求删除。

问题3：最新版本ik生效，是否还需拷贝配置文件到elasticsearch/config目录下？ 此项也没有详细说明，按以前的搜索结果，和issues中2015年的回答，是需要拷贝过去，但最新版本ik编译打包后目录结构有变化，不知是否还需拷贝。如果需要拷贝，需要拷贝哪些文件？

谢谢。

**Comment by medcl** [comment]
1.不需要加空格才对
2.如果你只是简单的使用，是不需要新增配置的，如果你需要自定义analyzer，才需要
3.配置文件不用拷贝的
新的README说明文件没有要求操作，说明是不需要

**Comment by Shasharoman** [comment]
docker启动的elasticsearch容器
ik安装方式 `plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v1.9.4/elasticsearch-analysis-ik-1.9.4.zip`

安装后启动报错：
Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at org.wltea.analyzer.dic.Dictionary.loadMainDict(Dictionary.java:237)
	at org.wltea.analyzer.dic.Dictionary.initial(Dictionary.java:107)
	at org.elasticsearch.indices.analysis.IKIndicesAnalysis.<init>(IKIndicesAnalysis.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

符合@conhaifeng说的问题三，手动copy config目录解决问题
