### ISSUE TITLE
ik 1.9.4 加载配置properteis文件报错

### ISSUE THREAD

**Issue by linkmancheng** [medcl/elasticsearch-analysis-ik#253]
已解压 plugin 文件到plugin目录，
日志报错：
java.lang.IllegalArgumentException: Plugin [${elasticsearch.plugin.name}] must be at least a jvm or site plugin
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:107)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)

发现其他插件的 plugin-descriptor.properties是固定的， 而ik是可以用变量的。ES可以支持么？

**Comment by medcl** [comment]
请问你是怎么安装的呢？你应该用release下面的文件，那个里面都是生成好的

**Comment by linkmancheng** [comment]
哦，是我的问题，我是直接用生成的jar包解压的。应当用生成的zip包，谢谢。

**Comment by selfconfidence** [comment]
????
