### ISSUE TITLE
Elasticsearch 1.5.0 + IK 1.3.0 无法运行~

### ISSUE THREAD

**Issue by occultskyrong** [medcl/elasticsearch-analysis-ik#254]
感谢medcl不厌其烦的教导我们~

系统版本 `CentOS release 6.5 (Final)`

Elasticsearch版本1.5.0
* Ik下载对应的[1.3.0](https://github.com/medcl/elasticsearch-analysis-ik/tree/v1.3.0)
直接从这个地址[https://github.com/medcl/elasticsearch-analysis-ik/archive/v1.3.0.tar.gz](https://github.com/medcl/elasticsearch-analysis-ik/archive/v1.3.0.tar.gz)下载的
* wget下载.tar.gz然后 tar解压缩,放在`./plugins/analysis-ik`
* 然后在`./config/elasticsearch.yml`的最后加上`index.analysis.analyzer.ik.type : "ik"`
* `./bin/elasticsearch` 重启后报错：
```
[2016-08-02 14:00:52,944][WARN ][indices.cluster          ] [ctcinfo] [.marvel-kibana] failed to create index
org.elasticsearch.indices.IndexCreationException: [.marvel-kibana] failed to create index
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:330)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:311)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:180)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:467)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer type [ik] or tokenizer for [ik]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:372)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:328)
	... 8 more
Caused by: org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [type] with value [ik]
	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:476)
	at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:464)
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:356)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.analysis.ik.IkAnalyzerProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:474)
	... 18 more
```

是不是什么地方没配置。。。看issue里面需要其他的各种配置。。。

`./plugins/analysis-ik/config/elasticseach.yml` 这个配置文件需要改动么？

**Comment by occultskyrong** [comment]
貌似我没有mvn package。。。。。。
参照1.3.0版本的说明
```
2.如何手动安装，以 1.3.0 為例？
`git clone https://github.com/medcl/elasticsearch-analysis-ik`
`cd elasticsearch-analysis-ik`
`mvn compile`
`mvn package`
`plugin —install analysis-ik —url file:///#{project_path}/elasticsearch-analysis-ik/target/releases/elasticsearch-analysis-ik-1.3.0.zip`
```

- [下载source] `wget https://github.com/medcl/elasticsearch-analysis-ik/archive/v1.3.0.tar.gz`
- [解压缩] `tar -zxvf v1.3.0.tar.gz` 解压后生成`elasticsearch-analysis-ik-1.3.0`
- [进入文件路径] ` cd elasticsearch-analysis-ik-1.3.0`
- [编译] `mvn compile`
- [打包] `mvn package`
- [安装] cd到Elasticsearch主路径，使用`bin/plugin --install analysis-ik --url file:///【此处为解压后elasticsearch-analysis-ik-1.3.0的路径】/elasticsearch-analysis-ik-1.3.0/target/releases/elasticsearch-analysis-ik-1.3.0.zip`
