### ISSUE TITLE
加入集群后ik_max_word分词器找不到

### ISSUE THREAD

**Issue by sxhyll** [medcl/elasticsearch-analysis-ik#27]
http://localhost:9200/standard_auction_names/_analyze?analyzer=ik_max_word&pretty=true&text=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD

 org.elasticsearch.index.mapper.MapperParsingException: Analyzer [ik_max_word] not found for field [description]

**Comment by xiezhw3** [comment]
Hi
我在配置 ik 分词的时候，elasticsearch 穷的哪个成功，加载情况是这样：
```
[2015-11-13 10:44:08,701][INFO ][node                     ] [Mikula Golubev] version[2.0.0], pid[3351], build[de54438/2015-10-22T08:09:48Z]                                
[2015-11-13 10:44:08,702][INFO ][node                     ] [Mikula Golubev] initializing ...
[2015-11-13 10:44:08,835][INFO ][plugins                  ] [Mikula Golubev] loaded [analysis-ik], sites []
[2015-11-13 10:44:08,859][INFO ][env                      ] [Mikula Golubev] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [38.9gb], net total_space [47.2gb], spins? [possibly], types [ext4]
[2015-11-13 10:44:10,046][INFO ][node                     ] [Mikula Golubev] initialized
[2015-11-13 10:44:10,046][INFO ][node                     ] [Mikula Golubev] starting ...
[2015-11-13 10:44:10,095][INFO ][transport                ] [Mikula Golubev] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2015-11-13 10:44:10,101][INFO ][discovery                ] [Mikula Golubev] elasticsearch/AkKPuS6bRqGmlgf_mHL1gw
[2015-11-13 10:44:13,154][INFO ][cluster.service          ] [Mikula Golubev] new_master {Mikula Golubev}{AkKPuS6bRqGmlgf_mHL1gw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2015-11-13 10:44:13,192][INFO ][http                     ] [Mikula Golubev] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2015-11-13 10:44:13,192][INFO ][node                     ] [Mikula Golubev] started
[2015-11-13 10:44:13,195][INFO ][gateway                  ] [Mikula Golubev] recovered [0] indices into cluster_state
[2015-11-13 10:45:31,790][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/mydict.dic
[2015-11-13 10:45:31,790][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/single_word_low_freq.dic
[2015-11-13 10:45:31,793][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/ext_stopword.dic
```
但是我在启动 ik 分词的时候，使用如下的方法：

```
curl -XPOST http://localhost:9200/index/fulltext/_mapping -d ' 
{
        "fulltext": {
             "_all": {
            "analyzer": "ik"
        },
       "properties": {
            "content": {
                "type" : "string",
                "boost" : 8.0,
                "term_vector" : "with_positions_offsets",
                "analyzer" : "ik",
                "include_in_all" : true
            }
        }
    }
}'
```
出现了下面的问题：

```
{
    "error": {
        "reason": "analyzer [ik] not found for field [content]",
        "root_cause": [
            {
                "reason": "analyzer [ik] not found for field [content]",
                "type": "mapper_parsing_exception"
            }
        ],
        "type": "mapper_parsing_exception"
    },
    "status": 400
}
```

我的 elasticsearch 版本是2.0.0，ik 版本是 1.5.0，我的 elasticsearch.yml 的配置是：

```
index.analysis.analyzer.ik.type : "ik"
```

有人知道这是什么原因么？

我试过另一种 elasticsearch.yml 配置：

```
index:
  analysis:                   
    analyzer:      
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true
index.analysis.analyzer.default.type: ik
```

但是在这种情况下 elasticsearch 无法启动成功！

希望知道原因的可以解答一下，谢谢！

**Comment by pi408637535** [comment]
type":"mapper_parsing_exception","reason":"analyzer [ik] not found for field [content]  这个是错误信息
下面的是我的启动日志：
[2016-11-24 20:26:08,352][WARN ][bootstrap                ] running as ROOT user. this is a bad idea!
[2016-11-24 20:26:08,579][INFO ][node                     ] [es-node1] version[2.4.1], pid[3133], build[c67dc32/2016-09-27T18:57:55Z]
[2016-11-24 20:26:08,580][INFO ][node                     ] [es-node1] initializing ...
[2016-11-24 20:26:09,219][INFO ][plugins                  ] [es-node1] modules [reindex, lang-expression, lang-groovy], plugins [head, hq, analysis-ik], sites [head, hq]
[2016-11-24 20:26:09,246][INFO ][env                      ] [es-node1] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [22.7gb], net total_space [49.9gb], spins? [unknown], types [rootfs]
[2016-11-24 20:26:09,246][INFO ][env                      ] [es-node1] heap size [989.8mb], compressed ordinary object pointers [true]
[2016-11-24 20:26:09,246][WARN ][env                      ] [es-node1] max file descriptors [4096] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-11-24 20:26:10,357][INFO ][ik-analyzer              ] try load config from /wode/soft/elastic/elasticsearch-2.4.1/config/analysis-ik/IKAnalyzer.cfg.xml
[2016-11-24 20:26:10,357][INFO ][ik-analyzer              ] try load config from /wode/soft/elastic/elasticsearch-2.4.1/plugins/ik/config/IKAnalyzer.cfg.xml
[2016-11-24 20:26:10,613][INFO ][ik-analyzer              ] [Dict Loading] custom/mydict.dic
[2016-11-24 20:26:10,613][INFO ][ik-analyzer              ] [Dict Loading] custom/single_word_low_freq.dic
[2016-11-24 20:26:10,615][INFO ][ik-analyzer              ] [Dict Loading] custom/ext_stopword.dic
[2016-11-24 20:26:10,864][INFO ][node                     ] [es-node1] initialized
[2016-11-24 20:26:10,864][INFO ][node                     ] [es-node1] starting ...
[2016-11-24 20:26:10,961][INFO ][transport                ] [es-node1] publish_address {118.244.212.185:9308}, bound_addresses {118.244.212.185:9308}
[2016-11-24 20:26:10,965][INFO ][discovery                ] [es-node1] wshare_es/W1u6s5AYQJSv-zsd_dVgSg
[2016-11-24 20:26:14,041][INFO ][cluster.service          ] [es-node1] new_master {es-node1}{W1u6s5AYQJSv-zsd_dVgSg}{118.244.212.185}{118.244.212.185:9308}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-11-24 20:26:14,139][INFO ][http                     ] [es-node1] publish_address {118.244.212.185:9208}, bound_addresses {118.244.212.185:9208}
[2016-11-24 20:26:14,139][INFO ][node                     ] [es-node1] started
[2016-11-24 20:26:14,174][INFO ][gateway                  ] [es-node1] recovered [0] indices into cluster_state
[2016-11-24 20:26:23,171][DEBUG][action.admin.indices.mapping.put] [es-node1] failed to put mappings on indices [[index]], type [fulltext]
MapperParsingException[analyzer [ik] not found for field [content]]
        at org.elasticsearch.index.mapper.core.TypeParsers.parseAnalyzersAndTermVectors(TypeParsers.java:220)
        at org.elasticsearch.index.mapper.core.TypeParsers.parseTextField(TypeParsers.java:250)
        at org.elasticsearch.index.mapper.core.StringFieldMapper$TypeParser.parse(StringFieldMapper.java:165)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:309)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:549)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
        at 
org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

我用的版本是:elasticsearch-2.4.1 iK:elasticsearch-analysis-ik-1.10.1 怎么都启动不起来。求救

**Comment by medcl** [comment]
没有 ik 了，只有 ik_smart 和 ik_maxword
