### ISSUE TITLE
5.0.0 beta1 crash

### ISSUE THREAD

**Issue by oldcai** [medcl/elasticsearch-analysis-ik#282]
```
[2016-09-28T00:47:19,977][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[4P1Tah_][clusterService#updateTask][T#1]], exiting
java.lang.NoSuchMethodError: org.elasticsearch.common.logging.Loggers.getLogger(Ljava/lang/String;)Lorg/elasticsearch/common/logging/ESLogger;
        at org.wltea.analyzer.dic.Dictionary.<clinit>(Dictionary.java:79) ~[?:?]
        at org.wltea.analyzer.cfg.Configuration.<init>(Configuration.java:47) ~[?:?]
        at org.elasticsearch.index.analysis.IkTokenizerFactory.<init>(IkTokenizerFactory.java:15) ~[?:?]
        at org.elasticsearch.index.analysis.IkTokenizerFactory.getIkTokenizerFactory(IkTokenizerFactory.java:19) ~[?:?]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:289) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:148) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:140) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
```

提示getLogger找不到方法

**Comment by oldcai** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/5.x/breaking_50_java_api_changes.html

这里说『Elasticsearch will no longer detect logging implementations』

**Comment by panqingfeng** [comment]
我也遇到这个问题了
