### ISSUE TITLE
Unknown Analyzer type [ik] for [default]

### ISSUE THREAD

**Issue by 653945222** [medcl/elasticsearch-analysis-ik#319]
es版本：2.1.1 
我通过下载ik 1.7 源码编译后将zip包放到plugins/ik目录下，并且在elasticsearch.yml 最后一行加入了 index.analysis.analyzer.default.type: ik
但是，es已启动就报错，
[2016-12-16 16:12:06,418][WARN ][cluster.action.shard     ] [es-01] [test111][2] received shard failed for [test111][2], node[HyUK1lQyQamVLJgdUudctg], [P], v[32], s[INITIALIZING], a[id=pqabSKcnT_e-gYuSMqEjhw], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-12-16T08:12:06.210Z], details[failed to create index, failure IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [default]]; ]], indexUUID [Uj5K1w-OQs2Wxh9cgVWfjg], message [failed to create index], failure [IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [default]]; ]
[test111] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [default]];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:307)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:176)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [ik] for [default]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:320)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
        at org.elasticsearch.indices.IndicesServ

**Comment by medcl** [comment]
没有 ik 类型了，拆分成了 ik_smart , ik_max_word， es 已经不支持配置文件配置默认分析器
