### ISSUE TITLE
ES 2.2.0 + IK 1.8.0: No feature for name [analyze=ik]

### ISSUE THREAD

**Issue by chentdy** [medcl/elasticsearch-analysis-ik#328]
您好，我的ES是2.2.0,下载了IK 1.8.0的版本编译，编译后将zip文件解压并放到了plugin目录下, 目录结构如下：
```
-rw-r--r--  1 tudouya  staff   258K  1 16 19:42 commons-codec-1.9.jar
-rw-r--r--  1 tudouya  staff    60K  1 16 19:42 commons-logging-1.2.jar
drwxr-xr-x  3 tudouya  staff   102B  2 20  2016 config
-rw-r--r--  1 tudouya  staff    67K  1 16 21:28 elasticsearch-analysis-ik-1.8.0.jar
-rw-r--r--  1 tudouya  staff   4.3M  1 16 21:29 elasticsearch-analysis-ik-1.8.0.zip
-rw-r--r--  1 tudouya  staff   704K  1 16 19:43 httpclient-4.4.1.jar
-rw-r--r--  1 tudouya  staff   315K  1 16 19:43 httpcore-4.4.1.jar
-rw-r--r--  1 tudouya  staff   2.6K  1 16 21:28 plugin-descriptor.properties
```
ES的配置文件没有增加任何配置，我按照文档插入了几条数据，但是在查询的时候，并不能查到结果，请问是不是哪里配置出错了,ES配置文件如下:
```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: es-cluster
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: es-master-node 
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /Users/tudouya/BigData/elasticsearch220/data 
#
# Path to log files:
#
path.logs: /Users/tudouya/BigData/elasticsearch220/logs 
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.mlockall: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
# index.analysis.analyzer.ik.type: "ik"

```
测试分词查询结果如下:
```
┌─[tudouya@chain-mac] - [~] - [2017-01-16 09:47:21]
└─[0] <> curl -XPOST http://localhost:9200/index/fulltext/_search  -d'
{
    "query" : { "term" : { "content" : "中国" }},
    "highlight" : {
        "pre_tags" : ["<tag1>", "<tag2>"],
        "post_tags" : ["</tag1>", "</tag2>"],
        "fields" : {
            "content" : {}
        }
    }
}
'
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
```
不能像文档示例那样查询结果。。。
==========================
如果ES配置文件加上如下配置:
```
index.analysis.analyzer.ik.type : "ik" 
```
启动ES时就会循环报错，不停的输出错误信息,:
```
galArgumentException[Unknown Analyzer type [ik] for [ik]]; ]], indexUUID [aI9qsAKeQsWgEvW9AaozRg], message [failed to create index], failure [IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [ik]]; ]
[index] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [ik]];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:294)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:163)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:600)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [ik] for [ik]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:320)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
        ... 9 more
[2017-01-16 22:02:42,579][INFO ][node                     ] [es-master-node] stopped
[2017-01-16 22:02:42,580][INFO ][node                     ] [es-master-node] closing ...
[2017-01-16 22:02:42,583][INFO ][node                     ] [es-master-node] closed
```

**Comment by medcl** [comment]
Hi,你不是直接放在 plugins 根目录的吧，需要有一个子目录的，参考：
https://github.com/medcl/elasticsearch-rtf/tree/master/plugins/analysis-ik

**Comment by chentdy** [comment]
@medcl 没有直接放在根目录的，只不过我的目录名称叫`ik`, 您这个示例是`analysis-ik`

**Comment by medcl** [comment]
这个没关系的

**Comment by medcl** [comment]
@chentdy  不要在 yml 文件里面进行配置，使用 setting 接口来配置 analyzer，
可以直接使用的 analyzer 有：
Analyzer: ik_smart , ik_max_word , Tokenizer: ik_smart , ik_max_word

**Comment by chentdy** [comment]
@medcl 是通过ES的setting接口来配置么?

**Comment by medcl** [comment]
@chentdy 是的

**Comment by chentdy** [comment]
@medcl  现在的情况是不用在配置文件任何配置，也不用通过setting接口来配置，直接就行了。
之前插入几条记录搜索的时候没有返回数据，貌似是curl编码的问题，我通过postman发请求，直接就返回结果了。
所以，确定下是2.2.0 + 1.8不用添加任何配置就能生效么？
我是看了这篇文章:[https://my.oschina.net/UpBoy/blog/620004](https://my.oschina.net/UpBoy/blog/620004) 试出来的。

**Comment by medcl** [comment]
不用配置就行了，如果有特殊需要才需要单独配置

**Comment by imWildCat** [comment]
settings 接口大概是这样的吗？
```bash
curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.analysis.analyzer.default.type" : "ik_max_word"
}'
```

**Comment by medcl** [comment]
@imWildCat 不是，通过 mapping 和 template 来设置默认的 analyzer。

```
curl -XDELETE http://localhost:9200/_template/rtf


curl -XPUT http://localhost:9200/ _template/rtf
-d'
{
  "template":   "*", 
  "settings": { "number_of_shards": 1 }, 
  "mappings": {
    "_default_": {
      "_all": { 
        "enabled": true
      },
      "dynamic_templates": [
        {
          "strings": { 
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "analyzer":"ik_max_word",
              "ignore_above": 256,
              "fields": {
                "keyword": {
                  "type":  "keyword"
                }
              }
            }
          }
        }
      ]
    }
  }
}
'
```

**Comment by imWildCat** [comment]
@medcl 感谢！

不好意思，之前我忘了回复了。我最后是通过 elasticsearch-rails 的 mapping 设置完毕的。
