### ISSUE TITLE
elasticsearch 2.4升级5.0 ik分词出现异常

### ISSUE THREAD

**Issue by dongbo0737** [medcl/elasticsearch-analysis-ik#342]
原来使用的ik分词是1.10.1版本的，因为升级ES5.2升级分词版本到5.2.1 
分词出现问题：
Caused by: java.lang.IllegalArgumentException: Unknown tokenizer type [ik] for [my_tokenizer]
        at org.elasticsearch.index.analysis.AnalysisRegistry.getAnalysisProvider(AnalysisRegistry.java:387) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:338) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:176) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:154) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:146) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:363) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:425) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:458) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cluster.metadata.MetaDataIndexStateService$2.execute(MetaDataIndexStateService.java:173) ~[elasticsearch-5.2.1.jar:5.2.1]
        ... 11 more

还有个异常是：
analyzer [ik] not found for field [message]

模板已经改变了将ik修改为ik_max_word
{
    "order" : 0,
    "template" : "xxx-*",
    "settings" : {
      "index" : {
        "refresh_interval" : "3s",
        "analysis" : {
          "filter" : {
            "camel_filter" : {
              "split_on_numerics" : "false",
              "type" : "word_delimiter",
              "stem_english_possessive" : "false",
              "generate_number_parts" : "false",
              "protected_words" : [
                "iPhone",
                "WiFi"
              ]
            }
          },
          "analyzer" : {
            "ik" : {
              "filter" : [
                "camel_filter",
                "lowercase"
              ],
              "char_filter" : [
                "html_strip"
              ],
              "type" : "custom",
              "tokenizer" : "my_tokenizer"
            }
          },
          "tokenizer" : {
            "my_tokenizer" : {
              "type" : "ik_max_word",
              "enable_lowercase" : "false"
            }
          }
        },
        "number_of_shards" : "20",
        "number_of_replicas" : "0"
      }
    },
    "mappings" : {
      "_default_" : {
        "dynamic_templates" : [
          {
            "message_field" : {
              "mapping" : {
                "analyzer" : "ik",
                "index" : "analyzed",
                "omit_norms" : true,
                "type" : "string"
              },
              "match_mapping_type" : "string",
              "match" : "message"
            }
          },
          {
            "logid_field" : {
              "mapping" : {
                "type" : "long"
              },
              "match_mapping_type" : "string",
              "match" : "logid"
            }
          },
          {
            "string_fields" : {
              "mapping" : {
                "index" : "not_analyzed",
                "omit_norms" : true,
                "type" : "string",
                "fields" : {
                  "raw" : {
                    "ignore_above" : 256,
                    "index" : "not_analyzed",
                    "type" : "string"
                  }
                }
              },
              "match_mapping_type" : "string",
              "match" : "*"
            }
          }
        ]
}

**Comment by dongbo0737** [comment]
已经解决，需要修改setting中的分词设置，不是template中的
