### ISSUE TITLE
如何配合ESIntegTestCase的client()进行ik插件单元测试？

### ISSUE THREAD

**Issue by hzysmail** [medcl/elasticsearch-analysis-ik#372]
目前在单元测试时返回如下异常信息，请问一下应该如何进行单元测试？
java.lang.IllegalArgumentException: failed to find global tokenizer under [ik_smart]
	at __randomizedtesting.SeedInfo.seed([437B4247ADF8664C:1EBB5BB8FB443572]:0)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:565)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:173)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:148)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:75)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by tenlee2012** [comment]
+1
