### ISSUE TITLE
分词报空指针

### ISSUE THREAD

**Issue by XisonChen** [medcl/elasticsearch-analysis-ik#432]
我用的版本是5.5.2
http://localhost:9200/user/_analyze?analyzer=ik_max_word&text=无敌是多么的寂寞
Caused by: java.lang.NullPointerException
        at org.wltea.analyzer.dic.Dictionary.isStopWord(Dictionary.java:334) ~[?:?]
        at org.wltea.analyzer.core.AnalyzeContext.getNextLexeme(AnalyzeContext.java:316) ~[?:?]
        at org.wltea.analyzer.core.IKSegmenter.next(IKSegmenter.java:95) ~[?:?]
        at org.wltea.analyzer.lucene.IKTokenizer.incrementToken(IKTokenizer.java:88) ~[?:?]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:209) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:157) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:77) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.2.jar:5.5.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by XisonChen** [comment]
IKAnalyzer.cfg.xml没有改配置导致

**Comment by chentaikuang** [comment]
没有改什么配置

**Comment by bikerr** [comment]
> IKAnalyzer.cfg.xml没有改配置导致

能否可以解释详细一点？

**Comment by Iamxf** [comment]
我也遇到这问题了，怎么解决的呢

**Comment by 6heng** [comment]
我也遇到过此问题
环境：es版本6.2.2， elasticsearch-analysis-ik-6.2.2.zip ，nginx1.21.3 
解决方案：
1.下载 https://github.com/medcl/elasticsearch-analysis-ik/tree/6.x 这个分支，修改pom.xml中es版本，然后编译
2.把编译后的zip包替代原有的插件包，然后修改/elasticsearch/plugins/ik/config/IKAnalyzer.cfg.xml中配置
3.重启es
如果上述操作完成，发现没有走远程分词库，可能是nginx版本太低，可以尝试升级下nginx
