### ISSUE TITLE
elasticsearch 1.4.0不能愉快的添加elasticsearch-analysis-ik

### ISSUE THREAD

**Issue by v5tech** [medcl/elasticsearch-analysis-ik#46]
通过源码自己build的elasticsearch-analysis-ik。配置好elasticsearch-analysis-ik，启动的时候报错，求大神更新。

```
Exception in thread "Thread-3" java.lang.NullPointerException
        at org.wltea.analyzer.dic.Monitor.run(Monitor.java:87)
        at java.lang.Thread.run(Thread.java:745)
org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:106)
        at org.wltea.analyzer.dic.Monitor.run(Monitor.java:64)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.ProtocolException: Target host is not specified
        at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultR
outePlanner.java:69)
        at org.apache.http.impl.client.InternalHttpClient.determineRoute(Interna
lHttpClient.java:124)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:183)
        ... 4 more
Exception in thread "Thread-4" java.lang.NullPointerException
        at org.wltea.analyzer.dic.Monitor.run(Monitor.java:87)
        at java.lang.Thread.run(Thread.java:745)
[2014-11-18 16:48:27,134][INFO ][mmseg-analyzer           ] chars loaded time=50
8ms, line=12638, on file=chars.dic
[2014-11-18 16:48:27,149][INFO ][mmseg-analyzer           ] words loaded time=2m
s, line=4, on file=words-my.dic
[2014-11-18 16:48:27,379][INFO ][mmseg-analyzer           ] words loaded time=22
7ms, line=157202, on file=words.dic
[2014-11-18 16:48:27,380][INFO ][mmseg-analyzer           ] load all dic use tim
e=754ms
[2014-11-18 16:48:27,382][INFO ][mmseg-analyzer           ] unit loaded time=1ms
, line=22, on file=units.dic
[2014-11-18 16:48:28,196][INFO ][gateway                  ] [Son of Satan] recov
ered [2] indices into cluster_state
[2014-11-18 16:52:12,078][INFO ][node                     ] [Son of Satan] stopp
ing ...
[2014-11-18 16:52:13,141][ERROR][marvel.agent.exporter    ] [Son of Satan] error
 sending data
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:182)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
```

卸载elasticsearch-analysis-ik后启动ok

**Comment by znketophawk** [comment]
![image](https://cloud.githubusercontent.com/assets/16219654/11678774/d8df8b42-9e85-11e5-85c3-5d8c401ffb59.png)
请问一下，这个里面是怎么配置的？这里面全是注释掉的代码，我在最下边加入代码以后，启动的时候报错。求解

**Comment by znketophawk** [comment]
![image](https://cloud.githubusercontent.com/assets/16219654/11678922/35d4b6b4-9e87-11e5-814e-1a46b8736ac0.png)
报这个错。配置文件写法

**Comment by medcl** [comment]
@znketophawk 不用改任何配置的

**Comment by znketophawk** [comment]
但是我自己定义完分词库以后，好像没有什么效果。。。。。蒙了，方便 QQ联系么？

**Comment by medcl** [comment]
@znketophawk 需要重建数据哦，
QQ群：190605846 和 论坛http://elasticsearch.cn

**Comment by qq4628241** [comment]
D:\My Tools\ElasticSearch\elasticsearch-2.1.1\bin>elasticsearch.bat
[2016-10-28 15:21:39,398][WARN ][bootstrap                ] unable to install syscall filter: syscall filtering not supported for OS: 'Windows 8.1'
[2016-10-28 15:21:39,866][INFO ][node                     ] [Silverclaw] version[2.1.1], pid[3464], build[40e2c53/2015-12-15T13:05:55Z]
[2016-10-28 15:21:39,866][INFO ][node                     ] [Silverclaw] initializing ...
[2016-10-28 15:21:40,382][INFO ][plugins                  ] [Silverclaw] loaded [elasticsearch-analysis-ik], sites [head]
[2016-10-28 15:21:40,414][INFO ][env                      ] [Silverclaw] using [1] data paths, mounts [[(D:)]], net usable_space [203.4gb], net total_space [376.8gb], spins? [unknown], types [NTFS]
Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\My%20Tools\ElasticSearch\elasticsearch-2.1.1\plugins\ik\config\ik\IKAnalyzer.cfg.xml" "read")

参考elasticsearch-analysis-ik安装说明安装，在启动es时报错.win10系统, ik1.7.0, elasticsearch-2.1.1.求解

**Comment by beiyoufx** [comment]
@qq4628241 路径不能包含空格
