### ISSUE TITLE
es6.0启动报错

### ISSUE THREAD

**Issue by kkrgwbj** [medcl/elasticsearch-analysis-ik#463]
@medcl 你好，es6.0启动报错。
###
Caused by: java.nio.file.NoSuchFileException: D:\Program Files\Java\elasticsearch-6.0.0\plugins\elasticsearch-analysis-ik-6.0.0\plugin-descriptor.properties
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:1.8.0_144]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_144]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_144]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_144]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_144]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:123) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:80) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.0.jar:6.0.0]
	... 6 more
###

**Comment by medcl** [comment]
已更新，https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.0.0
