### ISSUE TITLE
version error, plugin analysis-ik 5.6.3 is incompatible with version 5.6.5.

### ISSUE THREAD

**Issue by NeverMin** [medcl/elasticsearch-analysis-ik#476]
```
root@host:~#  /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.3/elasticsearch-analysis-ik-5.6.3.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.3/elasticsearch-analysis-ik-5.6.3.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: plugin [analysis-ik] is incompatible with version [5.6.5]; was designed for version [5.6.3]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:501)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
root@host:~#  curl http://localhost:9200/?pretty
{
  "name" : "ZdnnJ17",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "xxxxxxxxxx",
  "version" : {
    "number" : "5.6.3",
    "build_hash" : "1a2f265",
    "build_date" : "2017-10-06T20:33:39.012Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by NeverMin** [comment]
just upgrade elasticsearch to 5.6.5
