### ISSUE TITLE
How do Install ik to Elasticsearch 6.01

### ISSUE THREAD

**Issue by arliangtw** [medcl/elasticsearch-analysis-ik#479]
elasticsearch-6.0.1/bin/./elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.0.0/elasticsearch-analysis-ik-6.0.0.zip
`-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.0.0/elasticsearch-analysis-ik-6.0.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: plugin [analysis-ik] is incompatible with version [6.0.1]; was designed for version [6.0.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:155)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:532)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:601)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:204)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
`

**Comment by suwenjiang** [comment]
Get the same issue. 
when unzip and copy the Ik to ES plugin directory, the ES service would stop automatically. 

Regards,

**Comment by stayfool** [comment]
@suwenjiang @arliangtw clone the master, and change the version in pom.xml to 6.0.1, then follow the README.MD

**Comment by suwenjiang** [comment]
thanks @stayfool . With your suggestion, I came across a new issue create the index. Any idea will be appreciated. 

{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "unknown setting [index.properties.content.analyzer] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "unknown setting [index.properties.content.analyzer] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
    },
    "status": 400
}

**Comment by suwenjiang** [comment]
Resolved all the issues by updating the ES to 6.1.1 and clone and compile the master.

**Comment by arliangtw** [comment]
thanks @suwenjiang @stayfool  
I updating the ES to 6.1.1 and  clone and compile the master ，it is normal.
