### ISSUE TITLE
v5.6.8 index null_pointer_exception

### ISSUE THREAD

**Issue by daorren** [medcl/elasticsearch-analysis-ik#533]
tried to insert documents and got 500 null_pointer_exception
```
I20180403-09:45:14.708(8)? Elasticsearch TRACE: 2018-04-03T01:45:14Z
I20180403-09:45:14.708(8)?   -> POST http://xx.xx.xx.xx:9200/weaworking-messages/message/etQv2Eq8dAQtfWXk9
I20180403-09:45:14.708(8)?   {
I20180403-09:45:14.709(8)?     "rosterId": "RyW5hiXJjGDQme7o6",
I20180403-09:45:14.709(8)?     "threadId": "vy6q3Zgt8mGr7Ntth",
I20180403-09:45:14.709(8)?     "content": "[呆][呆]",
I20180403-09:45:14.710(8)?     "contentType": "TEXT",
I20180403-09:45:14.710(8)?     "createdAt": "2018-01-16T07:12:22.868Z",
I20180403-09:45:14.710(8)?     "imMsgId": "Cz7wpASnPdbfLykxg",
I20180403-09:45:14.711(8)?     "state": "active",
I20180403-09:45:14.711(8)?     "updatedAt": "2018-01-16T07:12:23.080Z",
I20180403-09:45:14.716(8)?     "meta": {
I20180403-09:45:14.717(8)?       "summary": "\n[呆][呆]\n"
I20180403-09:45:14.717(8)?     }
I20180403-09:45:14.717(8)?   }
I20180403-09:45:14.717(8)?   <- 500
I20180403-09:45:14.717(8)?   {
I20180403-09:45:14.718(8)?     "error": {
I20180403-09:45:14.718(8)?       "root_cause": [
I20180403-09:45:14.718(8)?         {
I20180403-09:45:14.718(8)?           "type": "null_pointer_exception",
I20180403-09:45:14.719(8)?           "reason": null
I20180403-09:45:14.719(8)?         }
I20180403-09:45:14.719(8)?       ],
I20180403-09:45:14.719(8)?       "type": "null_pointer_exception",
I20180403-09:45:14.719(8)?       "reason": null
I20180403-09:45:14.719(8)?     },
I20180403-09:45:14.720(8)?     "status": 500
I20180403-09:45:14.720(8)?   }
```

ES logs showed that error may come from ik

```
[2018-04-03T01:45:14,505][WARN ][r.suppressed             ] path: /weaworking-messages/message/etQv2Eq8dAQtfWXk9, params: {index=weaworking-messages,
id=etQv2Eq8dAQtfWXk9, type=message}
java.lang.NullPointerException: null
        at org.wltea.analyzer.dic.Dictionary.isStopWord(Dictionary.java:334) ~[?:?]
        at org.wltea.analyzer.core.AnalyzeContext.getNextLexeme(AnalyzeContext.java:316) ~[?:?]
        at org.wltea.analyzer.core.IKSegmenter.next(IKSegmenter.java:95) ~[?:?]
        at org.wltea.analyzer.lucene.IKTokenizer.incrementToken(IKTokenizer.java:88) ~[?:?]
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:746) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2da
be7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:447) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7
b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:403) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2da
be7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b
64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:478) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c47
2de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1571) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c2
98683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1316) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c2986
83 - varunthacker - 2017-08-29 21:54:39]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:662) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:606) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:504) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:557) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:546) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:493) ~[elasticsearch-5.6.
8.jar:5.6.8]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:146) ~[elasticsearch-5.6.8.jar:
5.6.8]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:115) ~[elasticsearch-5.6.8.jar
:5.6.8]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:70) ~[elasticsearch-5.6.8.jar:
5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:975)
~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:944)
~[elasticsearch-5.6.8.jar:5.6.8]
at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:345)
[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:270)
[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924) [elasticsearch-5.
6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:921) [elasticsearch-5.
6.8.jar:5.6.8]
        at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1659) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:933) [
elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:92) [elasticsearch-5.6.8
.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291) [elas
ticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicati
onAction.java:266) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicati
onAction.java:248) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.8
.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.8.jar:5.6.8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by medcl** [comment]
mapping 有么，用的 ik_smart 还是 ik_maxword？

**Comment by daorren** [comment]
mapping
```
mapping: {
    message: {
      properties: {
        content: {
          type: 'string',
          // term_vector: 'with_positions_offsets', // fast vector highlighter
          analyzer: 'my_ik_analyzer',
          search_analyzer: 'my_ik_analyzer',
        },
        contentType: {
          type: 'string',
          index : 'not_analyzed',
        },
        updatedAt: {
          type: 'date',
          index : 'not_analyzed',
        }
      }
    }
  }
```

**Comment by medcl** [comment]
IKAnalyzer.cfg.xml有修改过么，我默认配置测试貌似 ok

**Comment by daorren** [comment]
haven't modified any file of IK

just used ES official image, and installed plugins with command, and built new image

**Comment by daorren** [comment]
there's a error when es started
`java.io.FileNotFoundException: /usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml (No such file or directory)`

**Comment by medcl** [comment]
看起来是这个问题，plugin 方式安装会拷贝配置到 es 的配置目录，你在 docker 里面要挂载到外面的盘上去

**Comment by daorren** [comment]
Yes, suggestions below
1. in docker, we need `data/` and `plugins/` both  volume
2. download plugins into volume, grant all permissions, and name em exactly `analysis-ik` or `analysis-pinyin`

Thank you for help @medcl

**Comment by binderclip** [comment]
用了 @daorren 的方法，同时用解压安装的方式，就可以了。
这个错误估计是 config 的问题。在 https://github.com/medcl/elasticsearch-analysis-ik/issues/71 提到过。

**Comment by MerlinPong** [comment]
as @medcl said, use plugin-install command will overwrite the config of es, best way to install plugin is use volume.
