### ISSUE TITLE
修改IK 6.2.2分词器源码来基于mysql热更新词库,出现链接不上数据库

### ISSUE THREAD

**Issue by jackYangOY** [medcl/elasticsearch-analysis-ik#546]
我在用elasticsearch6.2.2安装IK6.2.2分词器的时候，一切正常，当使用IK 6.2.2分词器基于mysql热更新词库的时候链接不上数据库，用elasticsearch-5.2.0安装IK5.2.0基于mysql热更新词库一切正常，请问大家遇到过吗？
[2018-05-08T22:14:06,241][INFO ][o.w.a.d.Monitor          ] [==========]jdbc-reload.properties
[2018-05-08T22:14:06,246][INFO ][o.w.a.d.Monitor          ] [==========]jdbc.url=jdbc:mysql://localhost:3306/ik_dict?serverTimezone=GMT
[2018-05-08T22:14:06,250][INFO ][o.w.a.d.Monitor          ] [==========]jdbc.reload.sql=select word from hot_words
[2018-05-08T22:14:06,255][INFO ][o.w.a.d.Monitor          ] [==========]jdbc.reload.interval=1000
[2018-05-08T22:14:06,260][INFO ][o.w.a.d.Monitor          ] [==========]jdbc.reload.stopword.sql=select stopword as word from hot_stopwords
[2018-05-08T22:14:06,264][INFO ][o.w.a.d.Monitor          ] [==========]jdbc.user=root
[2018-05-08T22:14:06,268][INFO ][o.w.a.d.Monitor          ] [==========]jdbc.password=123456
[2018-05-08T22:14:06,273][INFO ][o.w.a.d.Monitor          ] [==========]query hot stopword dict from mysql, select stopword as word from hot_stopwords......
[2018-05-08T22:14:06,282][ERROR][o.w.a.d.Monitor          ] erorr
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.9.jar:?]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074) ~[mysql-connector-java-5.1.9.jar:?]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2209) ~[mysql-connector-java-5.1.9.jar:?]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.9.jar:?]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46) ~[mysql-connector-java-5.1.9.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.9.jar:?]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:352) ~[mysql-connector-java-5.1.9.jar:?]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:284) ~[mysql-connector-java-5.1.9.jar:?]

**Comment by klc025107** [comment]
同问这个问题

**Comment by Dog-Lee** [comment]
这是因为ES的plugin被限制使用权限。当然你也可以直接粗暴的在/usr/java/jdk1.8.0_151/jre/lib/security里修改java.policy。可以解决。但是更规范的做法是参考https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html#plugin-authors-jsm

我不过我尝试添加plugin-security.policy在ik插件根目录， 但是没有发现启动的有申请权限。还是会报无权限的异常。不知道medcl大大是否有什么解决办法

**Comment by medcl** [comment]
主要是我基本上不用热更新，这个功能造成的困扰实在是多过带来的便利

**Comment by Dog-Lee** [comment]
medcl大大，请问去哪里可以了解到您说的热更新造成的困扰？ 纯粹带着好奇与学习的心态提问。

**Comment by medcl** [comment]
@Dog-Lee  主要这么几点吧

- 权限设置问题
- 词库更新造成的旧索引的分词结果不一样，从而影响查询结果
- 网络请求连接失败的问题，issue 也有好几个
- 远程更新，集群层面需要保证每个节点都一致，目前是没有办法保证强一致的

**Comment by Dog-Lee** [comment]
刚刚我已经把plugin权限搞定了。主要的思路是：在本地配置好plugin-security.policy，当然因为是maven模块需要/assemblies/plugin.xml里面添加资源文件声明。之后需要使用./elasticsearch-pluin install file:///usr/xxxx 安装自己拓展的插件，es在安装的时候会提示你是否同意授权给该插件这些权限，同意之后就正常了。（不过似乎卸载后这些权限还存在，也就是如果remove plugin后再去plugin目录unzip插件，似乎也能拥有之前的权限，不清楚授权后的信息ES会存放在哪里）

第二第三第四，确实会出现这种情况。不过即使不使用热更新，手动添加词汇后重启ES，也应该会遇到旧索引分词结果不一样的情况。

所以我冒昧个人总结一下，用不用热更新机制，旧索引都需要reindex才能出现新加词汇的所有。

谢谢medcl大大。

**Comment by Dog-Lee** [comment]
是否可以将相关代码PR？

**Comment by neozo** [comment]
> @Dog-Lee 主要这么几点吧
> 
> * 权限设置问题
> * 词库更新造成的旧索引的分词结果不一样，从而影响查询结果
> * 网络请求连接失败的问题，issue 也有好几个
> * 远程更新，集群层面需要保证每个节点都一致，目前是没有办法保证强一致的

那目前有没有什么好的更新词库的方案，如果用本地词库，集群更新也很麻烦啊

**Comment by thank037** [comment]
> 刚刚我已经把plugin权限搞定了。主要的思路是：在本地配置好plugin-security.policy，当然因为是maven模块需要/assemblies/plugin.xml里面添加资源文件声明。之后需要使用./elasticsearch-pluin install file:///usr/xxxx 安装自己拓展的插件，es在安装的时候会提示你是否同意授权给该插件这些权限，同意之后就正常了。（不过似乎卸载后这些权限还存在，也就是如果remove plugin后再去plugin目录unzip插件，似乎也能拥有之前的权限，不清楚授权后的信息ES会存放在哪里）
> 
> 第二第三第四，确实会出现这种情况。不过即使不使用热更新，手动添加词汇后重启ES，也应该会遇到旧索引分词结果不一样的情况。
> 
> 所以我冒昧个人总结一下，用不用热更新机制，旧索引都需要reindex才能出现新加词汇的索引。
> 
> 谢谢medcl大大。

yes

**Comment by MisterLiWJ** [comment]
@medcl 大大,windows上面出现这个问题咋个解决呢,com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

**Comment by Dog-Lee** [comment]
@MisterLiWJ 温馨提示：该问题不属于IK分词。

数据库连接的相关问题不属于IK分词范畴。

**Comment by MisterLiWJ** [comment]
@Dog-Lee 你是怎么解决plugin权限问题呢,能否给份示例让我参考下
