### ISSUE TITLE
6.4.2Could not load plugin descriptor for plugin directory [commons-logging-1.2.jar]

### ISSUE THREAD

**Issue by tomlamcn** [medcl/elasticsearch-analysis-ik#609]
直接安装不行
jimbeamMac:elasticsearch Tom$ bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.4.2/elasticsearch-analysis-ik-6.4.2.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.4.2/elasticsearch-analysis-ik-6.4.2.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [commons-logging-1.2.jar]
	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:394)
	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:755)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:727)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:792)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.nio.file.FileSystemException: /usr/local/elasticsearch/plugins/commons-logging-1.2.jar/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162)
	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:391)
	... 14 more
------------------------------------------------------------------------------------------------------

解压的运行也是不行
jimbeamMac:bin Tom$ ./elasticsearch
[2018-11-01T17:41:11,230][INFO ][o.e.n.Node               ] [] initializing ...
[2018-11-01T17:41:11,310][INFO ][o.e.e.NodeEnvironment    ] [nQ0mOCc] using [1] data paths, mounts [[/ (/dev/disk1s1)]], net usable_space [38.2gb], net total_space [233.5gb], types [apfs]
[2018-11-01T17:41:11,310][INFO ][o.e.e.NodeEnvironment    ] [nQ0mOCc] heap size [989.8mb], compressed ordinary object pointers [true]
[2018-11-01T17:41:11,311][INFO ][o.e.n.Node               ] [nQ0mOCc] node name derived from node ID [nQ0mOCcSTgia-CK9-hVNFg]; set [node.name] to override
[2018-11-01T17:41:11,312][INFO ][o.e.n.Node               ] [nQ0mOCc] version[6.4.2], pid[6637], build[default/tar/04711c2/2018-09-26T13:34:09.098244Z], OS[Mac OS X/10.14/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_152-ea/25.152-b02]
[2018-11-01T17:41:11,312][INFO ][o.e.n.Node               ] [nQ0mOCc] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/var/folders/h0/_r8p6gfs6ldc5dn0ncw6p5r80000gn/T/elasticsearch.77C77uBU, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/usr/local/elasticsearch, -Des.path.conf=/usr/local/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
[2018-11-01T17:41:11,356][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [commons-logging-1.2.jar]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.2.jar:6.4.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.2.jar:6.4.2]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [commons-logging-1.2.jar]
	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:394) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:315) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.2.jar:6.4.2]
	... 6 more
Caused by: java.nio.file.FileSystemException: /usr/local/elasticsearch/plugins/commons-logging-1.2.jar/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_152-ea]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_152-ea]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_152-ea]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_152-ea]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:391) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:315) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.2.jar:6.4.2]
	... 6 more
jimbeamMac:bin Tom$ ls

**Comment by sky-yin** [comment]
在plugins目录下新建ik目录，然后把东西都放进去
重启es就行了

**Comment by flyingsea1213** [comment]
这个可能会帮到你： https://discuss.elastic.co/t/elasticsearch5-2-1-install-plugin-by-local-failure/79546/2
如果你把插件放到了plugins目录下，请把它移到其他地方，然后安装。
