### ISSUE TITLE
有es6.5.0么？报错java.lang.IllegalAccessError: tried to access class org.elasticsearch.common.logging.ESLoggerFactory from class org.wltea.analyzer.dic.Dictionary

### ISSUE THREAD

**Issue by 20170415** [medcl/elasticsearch-analysis-ik#620]
elasticsearch-analysis-ik master版本打包后plugin-descriptor.properties中显示为6.3.0版本，那么es6.5.0启动时会报错如下：
[2018-11-16T17:48:38,569][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [GQ03_cC] fatal error in thread [elasticsearch[GQ03_cC][generic][T#3]], exiting
java.lang.IllegalAccessError: tried to access class org.elasticsearch.common.logging.ESLoggerFactory from class org.wltea.analyzer.dic.Dictionary
	at org.wltea.analyzer.dic.Dictionary.<clinit>(Dictionary.java:87) ~[?:?]
	at org.wltea.analyzer.cfg.Configuration.<init>(Configuration.java:40) ~[?:?]
	at org.elasticsearch.index.analysis.IkTokenizerFactory.<init>(IkTokenizerFactory.java:15) ~[?:?]
	at org.elasticsearch.index.analysis.IkTokenizerFactory.getIkSmartTokenizerFactory(IkTokenizerFactory.java:23) ~[?:?]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:367) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:181) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:158) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:165) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:397) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:503) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:575) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.gateway.Gateway.performStateRecovery(Gateway.java:127) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.gateway.GatewayService$1.doRun(GatewayService.java:223) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.5.0.jar:6.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
请问这个问题是什么原因导致的呢？怎么解决呢？

**Comment by 03131302** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/pull/615#issue-231050466
做了个适配
