### ISSUE TITLE
elasticsearch 6.4.3 直接unzip方法 elasticsearch-analysis-ik 6.4.3 版本失败

### ISSUE THREAD

**Issue by ZhengZhongheng** [medcl/elasticsearch-analysis-ik#638]
下载了ik的6.4.3的ZIP包，然后unzip到 elasticsearch用户目录 plugin目录下，直接unzip，之后运行 elasticsearch，失败。看日志，报错如下：
[2018-12-24T16:43:04,546][ERROR][o.e.b.Bootstrap          ] Exception                                                             
java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [plugin-descriptor.properties]  _

如何解决？谢谢！

**Comment by ZhengZhongheng** [comment]
ES是 6.4.3版本，操作系统 centos 6.8。

**Comment by ZhengZhongheng** [comment]
[elasticsearch@cent1 plugins]$ ../bin/elasticsearch-plugin list
commons-codec-1.9.jar
Exception in thread "main" java.nio.file.FileSystemException: /elasticsearch-6.4.3/plugins/commons-codec-1.9.jar/plugin-descriptor.properties: 不是目录
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162)
        at org.elasticsearch.plugins.ListPluginsCommand.printPlugin(ListPluginsCommand.java:66)
        at org.elasticsearch.plugins.ListPluginsCommand.execute(ListPluginsCommand.java:60)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
[elasticsearch@cent1 plugins]$

**Comment by ZhengZhongheng** [comment]
我看到有说unzip后建立了一个目录，我这是解压在 plugin目录下。
[elasticsearch@cent1 plugins]$ ls -lrt
总用量 1428
-rw-r--r-- 1 elasticsearch elasticsearch 736658 5月   6 2018 httpclient-4.5.2.jar
-rw-r--r-- 1 elasticsearch elasticsearch  61829 5月   6 2018 commons-logging-1.2.jar
-rw-r--r-- 1 elasticsearch elasticsearch 326724 5月   6 2018 httpcore-4.4.4.jar
-rw-r--r-- 1 elasticsearch elasticsearch 263965 5月   6 2018 commons-codec-1.9.jar
drwxr-xr-x 2 elasticsearch elasticsearch   4096 8月  26 17:52 config
-rw-r--r-- 1 elasticsearch elasticsearch  52399 11月  9 10:50 elasticsearch-analysis-ik-6.4.3.jar
-rw-r--r-- 1 elasticsearch elasticsearch    125 11月  9 10:51 plugin-security.policy
-rw-r--r-- 1 elasticsearch elasticsearch   1805 11月  9 10:51 plugin-descriptor.properties
[elasticsearch@cent1 plugins]$ pwd
/elasticsearch-6.4.3/plugins
[elasticsearch@cent1 plugins]$

**Comment by ZhengZhongheng** [comment]
今天重新下载，使用 elasticsearch-plugin install 安装，仍旧报错不识别这个zip包。
[elasticsearch@cent1 plugins]$ ../bin/elasticsearch-plugin install ./elasticsearch-analysis-ik-6.4.3.zip -v
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin ./elasticsearch-analysis-ik-6.4.3.zip
[elasticsearch@cent1 plugins]$

**Comment by medcl** [comment]
手动解压，要在 plugin 下面建一个子目录。
命令安装请使用完整的路径访问符号 file:///xxx./xx.zip

**Comment by sujeek** [comment]
手动解压在plugins 目录下创建一个ik子目录，mkdir ik , 然后解压：unzip  -d /usr/local/opt/es/plugins/ik 
 xxx.zip
