### ISSUE TITLE
最新的es5.X官方源更新了5.6.14，而ik的还停留在5.6.13

### ISSUE THREAD

**Issue by nickfan** [medcl/elasticsearch-analysis-ik#649]
如题：
最新的es5.X官方源更新了5.6.14，而ik的还停留在5.6.13

```
Exception in thread "main" java.lang.IllegalArgumentException: plugin [analysis-ik] is incompatible with version [5.6.14]; was designed for version [5.6.13]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:501)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```
![image](https://user-images.githubusercontent.com/100613/51318710-07d00280-1a96-11e9-869d-2a6bebae7de1.png)

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.6.14
