### ISSUE TITLE
远程热词加上url后报空指针什么问题？

### ISSUE THREAD

**Issue by chentaikuang** [medcl/elasticsearch-analysis-ik#653]
![default](https://user-images.githubusercontent.com/4844083/53136953-eb0a7b80-35bb-11e9-9750-a5dc6693139c.png)

配置上远程分词，启动报错：
[2019-02-21T09:32:42,308][WARN ][o.e.g.Gateway            ] [1uhkUJ7] recovering index [nm_products/zpgaRYtGSQqnWK6vxBG8Iw] failed - recovering as closed
java.lang.NullPointerException: null
        at org.wltea.analyzer.dic.Dictionary.getRemoteWordsUnprivileged(Dictionary.java:471) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.lambda$getRemoteWords$0(Dictionary.java:448) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
        at org.wltea.analyzer.dic.Dictionary.getRemoteWords(Dictionary.java:447) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.loadRemoteExtDict(Dictionary.java:428) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.loadMainDict(Dictionary.java:402) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.initial(Dictionary.java:157) ~[?:?]
        at org.wltea.analyzer.cfg.Configuration.<init>(Configuration.java:40) ~[?:?]
        at org.elasticsearch.index.analysis.IkTokenizerFactory.<init>(IkTokenizerFactory.java:15) ~[?:?]
        at org.elasticsearch.index.analysis.IkTokenizerFactory.getIkSmartTokenizerFactory(IkTokenizerFactory.java:23) ~[?:?]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:367) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:181) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:158) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:165) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:397) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:503) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:575) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.gateway.Gateway.performStateRecovery(Gateway.java:127) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.gateway.GatewayService$1.doRun(GatewayService.java:223) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[2019-02-21T09:32:42,546][WARN ][o.e.x.s.a.s.m.NativeRoleMappingStore] [1uhkUJ7] Failed to clear cache for realms [[]]
[2019-02-21T09:32:42,606][INFO ][o.e.l.LicenseService     ] [1uhkUJ7] license [1ba1341c-c416-45a4-a37f-ceeb1bd44eef] mode [basic] - valid
[2019-02-21T09:32:42,621][INFO ][o.e.g.GatewayService     ] [1uhkUJ7] recovered [1] indices into cluster_state
[2019-02-21T09:32:42,742][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [1uhkUJ7] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2019-02-21T09:32:42,742][INFO ][o.e.n.Node               ] [1uhkUJ7] started

**Comment by chentaikuang** [comment]
@medcl 大神帮看看啥问题呀？

**Comment by chentaikuang** [comment]
String charset = "UTF-8";
// 获取编码，默认为utf-8
if (response.getEntity().getContentType().getValue().contains("charset=")) {
String contentType = response.getEntity().getContentType().getValue();
charset = contentType.substring(contentType.lastIndexOf("=") + 1);
}
-----------------------------
下载源码看，发现是getContentType()为空。远程词典方法没设置，就会抛错。
吐槽：底层源码竟然这么写，一口气写完代码！多加个判断，抛出信息清晰一点不好吗？

**Comment by medcl** [comment]
@chentaikuang 收到，感谢反馈。
