### ISSUE TITLE
加上远程扩展词典后分词报异常

### ISSUE THREAD

**Issue by chentaikuang** [medcl/elasticsearch-analysis-ik#654]
使用postman执行URL:
http://{{es_ipv4}}/_analyze?pretty
body:
{
  "analyzer": "ik_max_word",
  "text": "中国"
}
----------------------------
执行后报下面异常：
[2019-02-21T11:24:40,107][INFO ][o.w.a.d.Monitor          ] [xWlsYHE] [Dict Loading] http://localhost:8330/public/remoteDic/reload
[2019-02-21T11:24:40,939][WARN ][r.suppressed             ] [xWlsYHE] path: /_analyze, params: {pretty=}
org.elasticsearch.transport.RemoteTransportException: [xWlsYHE][XXX.XXX.XX.XX:9300][indices:admin/analyze[s]]
Caused by: java.lang.NullPointerException
        at org.wltea.analyzer.dic.Dictionary.getRemoteWordsUnprivileged(Dictionary.java:471) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.lambda$getRemoteWords$0(Dictionary.java:448) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
        at org.wltea.analyzer.dic.Dictionary.getRemoteWords(Dictionary.java:447) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.loadRemoteExtDict(Dictionary.java:428) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.loadMainDict(Dictionary.java:402) ~[?:?]
        at org.wltea.analyzer.dic.Dictionary.initial(Dictionary.java:157) ~[?:?]
        at org.wltea.analyzer.cfg.Configuration.<init>(Configuration.java:40) ~[?:?]
        at org.elasticsearch.index.analysis.IkAnalyzerProvider.<init>(IkAnalyzerProvider.java:15) ~[?:?]
        at org.elasticsearch.index.analysis.IkAnalyzerProvider.getIkAnalyzerProvider(IkAnalyzerProvider.java:25) ~[?:?]
        at org.elasticsearch.indices.analysis.AnalysisModule$AnalysisProvider.get(AnalysisModule.java:274) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.analysis.AnalysisRegistry.lambda$getAnalyzer$0(AnalysisRegistry.java:134) ~[elasticsearch-6.5.4.jar:6.5.4]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_181]
        at org.elasticsearch.index.analysis.AnalysisRegistry.getAnalyzer(AnalysisRegistry.java:132) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:177) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:165) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:112) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

--------------------
6.5.4远程分词怎么这么多问题？能出个配置的指导文档吗？

**Comment by chentaikuang** [comment]
@medcl

**Comment by popfaker** [comment]
请问你解决了吗，如何解决的？@c

> ## 使用postman执行URL:
> http://{{es_ipv4}}/_analyze?pretty
> body:
> {
> "analyzer": "ik_max_word",
> "text": "中国"
> }
> 执行后报下面异常：
> [2019-02-21T11:24:40,107][INFO ][o.w.a.d.Monitor ] [xWlsYHE] [Dict Loading] http://localhost:8330/public/remoteDic/reload
> [2019-02-21T11:24:40,939][WARN ][r.suppressed ] [xWlsYHE] path: /_analyze, params: {pretty=}
> org.elasticsearch.transport.RemoteTransportException: [xWlsYHE][XXX.XXX.XX.XX:9300][indices:admin/analyze[s]]
> Caused by: java.lang.NullPointerException
> at org.wltea.analyzer.dic.Dictionary.getRemoteWordsUnprivileged(Dictionary.java:471) ~[?:?]
> at org.wltea.analyzer.dic.Dictionary.lambda$getRemoteWords$0(Dictionary.java:448) ~[?:?]
> at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
> at org.wltea.analyzer.dic.Dictionary.getRemoteWords(Dictionary.java:447) ~[?:?]
> at org.wltea.analyzer.dic.Dictionary.loadRemoteExtDict(Dictionary.java:428) ~[?:?]
> at org.wltea.analyzer.dic.Dictionary.loadMainDict(Dictionary.java:402) ~[?:?]
> at org.wltea.analyzer.dic.Dictionary.initial(Dictionary.java:157) ~[?:?]
> at org.wltea.analyzer.cfg.Configuration.(Configuration.java:40) ~[?:?]
> at org.elasticsearch.index.analysis.IkAnalyzerProvider.(IkAnalyzerProvider.java:15) ~[?:?]
> at org.elasticsearch.index.analysis.IkAnalyzerProvider.getIkAnalyzerProvider(IkAnalyzerProvider.java:25) ~[?:?]
> at org.elasticsearch.indices.analysis.AnalysisModule$AnalysisProvider.get(AnalysisModule.java:274) ~[elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.index.analysis.AnalysisRegistry.lambda$getAnalyzer$0(AnalysisRegistry.java:134) ~[elasticsearch-6.5.4.jar:6.5.4]
> at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_181]
> at org.elasticsearch.index.analysis.AnalysisRegistry.getAnalyzer(AnalysisRegistry.java:132) ~[elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:177) ~[elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:165) ~[elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:112) [elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.4.jar:6.5.4]
> at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
> 
> 6.5.4远程分词怎么这么多问题？能出个配置的指导文档吗？

请问你解决了吗？如何解决的？
