### ISSUE TITLE
关于Ik中英分词查询问题

### ISSUE THREAD

**Issue by lclangcheng** [medcl/elasticsearch-analysis-ik#659]
环境使用：
   centos7
   使用es 6.3.0
   加载ik插件 6.3.0
索引信息：
```
{
      'settings': {
        'number_of_shards': 2,
        'number_of_replicas': 1,
        'max_result_window': 500000,
        'blocks': {
          'read_only_allow_delete': 'false'
        },
        'analysis': {
          'analyzer': {
            'my_ik_smart': {
              'type': 'custom',
              'tokenizer': 'ik_smart',
              'filter': [
                'word_delimiter'
              ]
            }
          }
        }
      },
      'mappings': {
        'index': {
          'properties': {
            'id': {
              'type': 'keyword'
            },
            'title': {
              'type': 'text',
              'analyzer': 'my_ik_smart',
              'search_analyzer': 'my_ik_smart'
            }
          }
        }
      }
}
```
使用你们的远程热更新分词，分词中有“中英合并的词”，查询的时候无法命中“中英合并的词”，
在分析“b站”词时，会被切分，
异常：
```
GET news/_analyze
{
  "analyzer":"my_ik_smart",
  "text": "B站"
}
```
返回
```
{
  "tokens": [
    {
      "token": "b",
      "start_offset": 0,
      "end_offset": 1,
      "type": "ENGLISH",
      "position": 0
    },
    {
      "token": "站",
      "start_offset": 1,
      "end_offset": 2,
      "type": "CN_CHAR",
      "position": 1
    }
  ]
}
```
正常：
```
GET news/_analyze
{
  "analyzer":"my_ik_smart",
  "text": "格力电器"
}
```
返回
```
{
  "tokens": [
    {
      "token": "格力电器",
      "start_offset": 0,
      "end_offset": 4,
      "type": "CN_WORD",
      "position": 0
    }
  ]
}
```
我试过如果分词全中文时没问题的，如果分词中包含英文或者数字时，分词就会被切分，请问如何才不被切分？

其次，如果ik分词中有“标普500”，那么在入库时会报错
现有数据插入“标普500ETF再成吸金利器”到title字段，发现报错

```
Error: [illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=5,lastStartOffset=2 for field 'title'
    at respond (/root/jin10_es_node/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/root/jin10_es_node/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/root/jin10_es_node/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/root/jin10_es_node/node_modules/lodash/lodash.js:4935:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)                                                                          
    at process._tickCallback (internal/process/next_tick.js:181:9)                                                                           
    status: 400,                                                                                                                             
    displayName: 'BadRequest',                                                                                                               
    message: '[illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=5,lastStartOffset=2 for field \'title\'',                                                                    
    path: '/alias_news/index/23166',                                                                                                         
    query: {},                                                                                                                               
    body: { error: [Object], status: 400 },                                                                                                  
    statusCode: 400,                                                                                                                         
    response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=5,lastStartOffset=2 for field \'title\'"}],"type":"illegal_argument_exception","reason":"startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=5,lastStartOffset=2 for field \'title\'"},"status":400}'

```

**Comment by lclangcheng** [comment]
已解决 filter里的word_delimiter问题
