### ISSUE TITLE
elasticsearch-1.5.2

### ISSUE THREAD

**Issue by tian-xiaobo** [medcl/elasticsearch-analysis-ik#68]
[2015-05-25 09:54:10,514][DEBUG][action.admin.indices.create] [Marvin Flumm] [krypton_production_posts] failed to create
org.elasticsearch.indices.IndexCreationException: [krypton_production_posts] failed to create index
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:330)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:372)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:365)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer type [ik] or tokenizer for [ik]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:372)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:328)
	... 7 more
Caused by: org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [type] with value [ik]
	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:476)
	at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:464)
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:356)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.analysis.ik.IkAnalyzerProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:474)
	... 17 more

**Comment by medcl** [comment]
针对1.6.0的版本:   https://github.com/medcl/elasticsearch-rtf/tree/1.6.0
