### ISSUE TITLE
elasticsearch-7.1.1 plugin install error

### ISSUE THREAD

**Issue by karezi** [medcl/elasticsearch-analysis-ik#693]
采用elasticsearch-plugin安装的方式出现以下错误：
```
D:\elasticsearch-7.1.1\bin>elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.1.1/elasticsearch-analysis-ik-7.1.1.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.1.1/elasticsearch-analysis-ik-7.1.1.zip
[=================================================] 100%??
Exception in thread "main" java.lang.IllegalStateException: failed to load plugin analysis-ik due to jar hell
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:524)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:765)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:728)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:793)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:776)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.lang.IllegalStateException: jar hell!
class: org.elasticsearch.index.analysis.IkAnalyzerProvider
jar1: D:\elasticsearch-7.1.1\lib\elasticsearch-analysis-ik-7.1.1.jar
jar2: D:\elasticsearch-7.1.1\plugins\.installing-973370306526538991\elasticsearch-analysis-ik-7.1.1.jar
        at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:282)
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:190)
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:522)
        ... 12 more
```
解压到plugins文件夹下安装也是一样的错误

**Comment by medcl** [comment]
错误里面说了，这个是你手动放的吧：`D:\elasticsearch-7.1.1\lib\elasticsearch-analysis-ik-7.1.1.jar`

**Comment by karezi** [comment]
> 错误里面说了，这个是你手动放的吧：`D:\elasticsearch-7.1.1\lib\elasticsearch-analysis-ik-7.1.1.jar`

谢谢！确实忘记删了，删了就好了
