### ISSUE TITLE
org.elasticsearch.index.mapper.MapperParsingException: analyzer [ik_smart] not found for field [content]

### ISSUE THREAD

**Issue by heikehuan** [medcl/elasticsearch-analysis-ik#762]
`org.elasticsearch.index.mapper.MapperParsingException: analyzer [ik_smart] not found for field [content]
        at org.elasticsearch.index.mapper.TypeParsers.parseAnalyzersAndTermVectors(TypeParsers.java:127)
        at org.elasticsearch.index.mapper.TypeParsers.parseTextField(TypeParsers.java:209)
        at org.elasticsearch.index.mapper.TextFieldMapper$TypeParser.parse(TextFieldMapper.java:185)
        at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:277)
        at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:199)
        at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:102)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:111)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:91)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:633)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:264)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:633)
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:611)
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:570)
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:262)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)`

用代码创建索引，报这个异常

**Comment by medcl** [comment]
插件装好了么？

**Comment by heikehuan** [comment]
谢谢问题已解决，是线上配置问题。prod环境装了插件，但是后来发现，发布时发的prepare环境，没装插件，导致这个问题
