### ISSUE TITLE
【启动问题】 java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin

### ISSUE THREAD

**Issue by lzhbk** [medcl/elasticsearch-analysis-ik#768]
uncaught exception in thread [main]
ElasticsearchException[Could not find plugin class [org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin]]; nested: ClassNotFoundException[org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin];
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:864)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:581)
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:555)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163)
	at org.elasticsearch.node.Node.<init>(Node.java:313)
	at org.elasticsearch.node.Node.<init>(Node.java:257)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)

**Comment by Li-Yitian** [comment]
这个是什么原因有没有大神帮忙看看

**Comment by medcl** [comment]
上下文还有没有补充，是不是包安装不完整，补充之后再重新开启
