### ISSUE TITLE
热词更新怎么总出错呢？麻烦大神看看

### ISSUE THREAD

**Issue by starckgates** [medcl/elasticsearch-analysis-ik#79]
C:\Windows\system32>elasticsearch
[2015-08-04 10:33:44,414][INFO ][node                     ] [Mortimer Toynbee] version[1.6.0], pid[4380], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-08-04 10:33:44,419][INFO ][node                     ] [Mortimer Toynbee] initializing ...
[2015-08-04 10:33:44,502][INFO ][plugins                  ] [Mortimer Toynbee] loaded [analysis-pinyin, jdbc-1.5.0.5-da4ba96, support-1.6.0.0-d7bb0e9, analysis-ik], sites [head]
[2015-08-04 10:33:44,599][INFO ][env                      ] [Mortimer Toynbee] using [1] data paths, mounts [[(D:)]], net usable_space [36gb], net total_space [48.8gb], types [NT
[2015-08-04 10:33:49,237][INFO ][node                     ] [Mortimer Toynbee] initialized
[2015-08-04 10:33:49,240][INFO ][node                     ] [Mortimer Toynbee] starting ...
[2015-08-04 10:33:50,374][INFO ][transport                ] [Mortimer Toynbee] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.202.1:9300]}
[2015-08-04 10:33:50,991][INFO ][discovery                ] [Mortimer Toynbee] elasticsearch/XOrZfpXSQ4Str2sH0OiysA
[2015-08-04 10:33:54,841][INFO ][cluster.service          ] [Mortimer Toynbee] new_master [Mortimer Toynbee][XOrZfpXSQ4Str2sH0OiysA][jishu-liusong][inet[/192.168.202.1:9300]], re
[2015-08-04 10:33:55,255][INFO ][gateway                  ] [Mortimer Toynbee] recovered [6] indices into cluster_state
[2015-08-04 10:33:56,292][INFO ][http                     ] [Mortimer Toynbee] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.202.1:9200]}
[2015-08-04 10:33:56,295][INFO ][node                     ] [Mortimer Toynbee] started
[2015-08-04 10:33:56,330][INFO ][ik-analyzer              ] [Dict Loading]ik\custom\mydict.dic
[2015-08-04 10:33:56,333][INFO ][ik-analyzer              ] [Dict Loading]ik\custom\single_word_low_freq.dic
[2015-08-04 10:33:56,343][INFO ][ik-analyzer              ] [Dict Loading]ik\custom\sougou.dic
[2015-08-04 10:33:56,865][INFO ][ik-analyzer              ] [Dict Loading]http://localhost/dict/
[2015-08-04 10:33:57,228][INFO ][ik-analyzer              ] medcl
[2015-08-04 10:33:57,231][INFO ][ik-analyzer              ] 浣?
[2015-08-04 10:33:57,234][INFO ][ik-analyzer              ] [Dict Loading]ik\custom\ext_stopword.dic
[2015-08-04 10:33:59,297][INFO ][river                    ] [Mortimer Toynbee] rivers have been deprecated. Read https://www.elastic.co/blog/deprecating_rivers
[2015-08-04 10:33:59,319][INFO ][river.jdbc.JDBCRiver     ] started river instance for single run
[2015-08-04 10:33:59,391][INFO ][river                    ] [Mortimer Toynbee] rivers have been deprecated. Read https://www.elastic.co/blog/deprecating_rivers
[2015-08-04 10:33:59,397][INFO ][river.jdbc.JDBCRiver     ] started river instance for single run
[2015-08-04 10:33:59,404][INFO ][river                    ] [Mortimer Toynbee] rivers have been deprecated. Read https://www.elastic.co/blog/deprecating_rivers
[2015-08-04 10:33:59,412][INFO ][river.jdbc.JDBCRiver     ] started river instance for single run
[2015-08-04 10:34:00,036][INFO ][index.shard              ] [Mortimer Toynbee] [tag][2] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,050][INFO ][index.shard              ] [Mortimer Toynbee] [tag][1] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,056][INFO ][index.shard              ] [Mortimer Toynbee] [tag][3] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,062][INFO ][index.shard              ] [Mortimer Toynbee] [tag][0] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,068][INFO ][index.shard              ] [Mortimer Toynbee] [tag][4] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,103][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][0] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,114][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][4] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,120][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][2] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,179][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][3] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,186][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][1] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,273][INFO ][index.shard              ] [Mortimer Toynbee] [crm][4] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,281][INFO ][index.shard              ] [Mortimer Toynbee] [crm][2] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,285][INFO ][index.shard              ] [Mortimer Toynbee] [crm][3] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,300][INFO ][index.shard              ] [Mortimer Toynbee] [crm][1] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:00,304][INFO ][index.shard              ] [Mortimer Toynbee] [crm][0] updating refresh_interval from [1s] to [-1]
[2015-08-04 10:34:07,185][INFO ][index.shard              ] [Mortimer Toynbee] [crm][4] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:07,190][INFO ][index.shard              ] [Mortimer Toynbee] [crm][2] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:07,200][INFO ][index.shard              ] [Mortimer Toynbee] [crm][3] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:07,239][INFO ][index.shard              ] [Mortimer Toynbee] [crm][1] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:07,277][INFO ][index.shard              ] [Mortimer Toynbee] [crm][0] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:07,475][ERROR][ik-analyzer              ] remote_ext_dict http://localhost/dict/ error!
java.lang.NullPointerException
        at org.wltea.analyzer.dic.Monitor.run(Monitor.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-08-04 10:34:10,144][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@4e3b673c complete: river jdbc/SMS_river metrics: 8633 rows,
[2015-08-04 10:34:15,526][INFO ][index.shard              ] [Mortimer Toynbee] [tag][2] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:15,569][INFO ][index.shard              ] [Mortimer Toynbee] [tag][1] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:15,605][INFO ][index.shard              ] [Mortimer Toynbee] [tag][3] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:15,687][INFO ][index.shard              ] [Mortimer Toynbee] [tag][0] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:15,770][INFO ][index.shard              ] [Mortimer Toynbee] [tag][4] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:17,703][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@690b733d complete: river jdbc/Tag_river metrics: 27505 rows,
[2015-08-04 10:34:20,382][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][0] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:20,397][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][4] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:20,412][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][2] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:20,423][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][3] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:20,434][INFO ][index.shard              ] [Mortimer Toynbee] [sci_news][1] updating refresh_interval from [-1] to [1s]
[2015-08-04 10:34:22,023][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@773bbf17 complete: river jdbc/news metrics: 2968 rows, 130.7

------------------------------------------------------------------------------------------------------
IKAnalyzer.cfg.xml
------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">  
<properties>  
	<comment>IK Analyzer 扩展配置</comment>
		
	<entry key="ext_dict">custom/mydict.dic;custom/single_word_low_freq.dic;custom/sougou.dic</entry> 	
	 
	<entry key="ext_stopwords">custom/ext_stopword.dic</entry>
		
	<entry key="remote_ext_dict">http://localhost/dict/</entry>
	
	
</properties>
------------------------------------------------------------------------------------------------------
Default.aspx
--------------------------
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApp.dict.Default" %>
------------------------------------------------------------------------------------------------------
Default.aspx.cs
--------------------------
string[] lines = File.ReadAllLines("E:\\ForSearch\\ForSearch_v1.0\\WebApp\\dict\\updict.dic");
            foreach (string line in lines)
            {
                Response.Write(line+"\n");
            }

**Comment by medcl** [comment]
http://localhost/dict/  这个路径打不开,IKAnalyzer.cfg.xml你去掉远程路径吧

**Comment by starckgates** [comment]
@medcl 大神，我这个路径是本地测试路径，没有外网url的，IKAnalyzer.cfg.xml里是这么调用的，代码里已经写出了。
大神可否给个有返回值的示例代码呢？
谢谢大神。
另外请教大神一个Elasticsearch的问题，为什么使用query_string搜索，没有的内容也能搜出来？比如索引里本来没有这个词，但是搜这个词的时候却能把这条数据也搜出来？
