### ISSUE TITLE
mac下没有config配置文件夹的问题, 无法自定义词典

### ISSUE THREAD

**Issue by bode135** [medcl/elasticsearch-analysis-ik#875]
使用`./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.3.0/elasticsearch-analysis-ik-6.3.0.zip`安装的7.10.2版本  

安装后`plugins`目录结构如下:
- ls命令
![image](https://user-images.githubusercontent.com/40768803/116531426-bcae2680-a911-11eb-9d7f-7b77b7e3c91c.png)
- tree命令
![image](https://user-images.githubusercontent.com/40768803/116531574-e8c9a780-a911-11eb-931b-2f1c71b8f047.png)

我想自定义词典, 但我找不到Readme里面说的"conf"文件夹.
```
Dictionary Configuration
IKAnalyzer.cfg.xml can be located at {conf}/analysis-ik/config/IKAnalyzer.cfg.xml or {plugins}/elasticsearch-analysis-ik-*/config/IKAnalyzer.cfg.xml
```

我尝试了手动下载然后解压, 但`elasticsearch-plugin list`报错了.
```
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
.DS_Store
Exception in thread "main" java.nio.file.FileSystemException: /usr/local/Cellar/elasticsearch/7.10.2/libexec/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
	at org.elasticsearch.plugins.ListPluginsCommand.printPlugin(ListPluginsCommand.java:66)
	at org.elasticsearch.plugins.ListPluginsCommand.execute(ListPluginsCommand.java:60)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

尝试重启然后连接<http://localhost:9200/>也无法打开.  
请问如何解决呢?

**Comment by bode135** [comment]
重启es能成功, 就是打不开9200端口.
```
brew services start elasticsearch
brew services restart elasticsearch
```
![image](https://user-images.githubusercontent.com/40768803/116532992-78238a80-a913-11eb-8d10-e95b92907e1c.png)


![image](https://user-images.githubusercontent.com/40768803/116533087-9093a500-a913-11eb-93ca-2daa570d00d5.png)

**Comment by bode135** [comment]
已解决, mac下用brew安装的话, 路径跟linux&windows不同.  
用tree命令看一下文件结构就能找到config了

**Comment by yuusha-walter** [comment]
不知道什么原因，配置文件改放到了 `/usr/share/elasticsearch/config/analysis-ik/` 下。浪费了很多时间才找到，被恶心到了
