### ISSUE TITLE
如何写一个测试类 把代码跑起来 求大佬

### ISSUE THREAD

**Issue by jiujiwudixyx** [medcl/elasticsearch-analysis-ik#910]
![image](https://user-images.githubusercontent.com/71392455/134868809-9cf71ec0-f3de-4ffe-b0be-0de14d9892b0.png)
这里Setting的构造器私有了

**Comment by zth1993** [comment]
public static void main(String[] args) throws IOException {
        Settings settings = Settings.builder()
                .put("use_samrt", false)
                .put("enable_lowercase", false)
                .put("enable_remote_dict", false)
                .build();

        Configuration configuration = new Configuration(null, settings);
        IKSegmenter ikSegmenter = new IKSegmenter(new StringReader(text), configuration);
        Lexeme next;

        while ((next = ikSegmenter.next()) != null) {
            System.out.println(next.getLexemeText());
        }
    }


报错：
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.NullPointerException
	at org.wltea.analyzer.dic.Dictionary.<init>(Dictionary.java:106)
	at org.wltea.analyzer.dic.Dictionary.initial(Dictionary.java:150)
	at org.wltea.analyzer.cfg.Configuration.<init>(Configuration.java:40)
	at org.wltea.analyzer.Test.main(Test.java:29)

**Comment by zth1993** [comment]
错误原因是 Configuration 第一个参数不能为null

**Comment by kin122** [comment]
@zjz1993 @zth1993 @jiujiwudixyx 现在可以借助ai写一个，如果还有问题可以重开这个issue
